// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: master.proto
//
// gRPC ripped: this file holds only the grpc-free Hanzo (master) contracts. The
// client interface returns the shared rpc.* stream seams; the server interface
// is a plain method set (no mustEmbed) whose streaming RPCs take grpc-free bidi
// seams. The transport is github.com/zap-proto/go — the ZAP adapters in package
// masterzap satisfy the client, and the master engine satisfies the server,
// dispatched by the wire (unary) and masterstream (streaming) servers. No grpc
// client/server scaffolding remains.

package master_pb

import (
	context "context"

	"github.com/hanzoai/s3/s3/pb/rpc"
)

const (
	Hanzo_SendHeartbeat_FullMethodName          = "/master_pb.Hanzo/SendHeartbeat"
	Hanzo_KeepConnected_FullMethodName          = "/master_pb.Hanzo/KeepConnected"
	Hanzo_LookupVolume_FullMethodName           = "/master_pb.Hanzo/LookupVolume"
	Hanzo_Assign_FullMethodName                 = "/master_pb.Hanzo/Assign"
	Hanzo_StreamAssign_FullMethodName           = "/master_pb.Hanzo/StreamAssign"
	Hanzo_Statistics_FullMethodName             = "/master_pb.Hanzo/Statistics"
	Hanzo_CollectionList_FullMethodName         = "/master_pb.Hanzo/CollectionList"
	Hanzo_CollectionDelete_FullMethodName       = "/master_pb.Hanzo/CollectionDelete"
	Hanzo_VolumeList_FullMethodName             = "/master_pb.Hanzo/VolumeList"
	Hanzo_LookupEcVolume_FullMethodName         = "/master_pb.Hanzo/LookupEcVolume"
	Hanzo_VacuumVolume_FullMethodName           = "/master_pb.Hanzo/VacuumVolume"
	Hanzo_DisableVacuum_FullMethodName          = "/master_pb.Hanzo/DisableVacuum"
	Hanzo_EnableVacuum_FullMethodName           = "/master_pb.Hanzo/EnableVacuum"
	Hanzo_VolumeMarkReadonly_FullMethodName     = "/master_pb.Hanzo/VolumeMarkReadonly"
	Hanzo_GetMasterConfiguration_FullMethodName = "/master_pb.Hanzo/GetMasterConfiguration"
	Hanzo_ListClusterNodes_FullMethodName       = "/master_pb.Hanzo/ListClusterNodes"
	Hanzo_LeaseAdminToken_FullMethodName        = "/master_pb.Hanzo/LeaseAdminToken"
	Hanzo_ReleaseAdminToken_FullMethodName      = "/master_pb.Hanzo/ReleaseAdminToken"
	Hanzo_Ping_FullMethodName                   = "/master_pb.Hanzo/Ping"
	Hanzo_RaftListClusterServers_FullMethodName = "/master_pb.Hanzo/RaftListClusterServers"
	Hanzo_RaftAddServer_FullMethodName          = "/master_pb.Hanzo/RaftAddServer"
	Hanzo_RaftRemoveServer_FullMethodName       = "/master_pb.Hanzo/RaftRemoveServer"
	Hanzo_RaftLeadershipTransfer_FullMethodName = "/master_pb.Hanzo/RaftLeadershipTransfer"
	Hanzo_VolumeGrow_FullMethodName             = "/master_pb.Hanzo/VolumeGrow"
)

// HanzoClient is the client API for the Hanzo (master) service. Unary RPCs
// return the response; the three streaming RPCs are bidirectional and return an
// rpc.BidiStream seam written with Send and read with Recv (CloseSend to
// half-close the send side).
type HanzoClient interface {
	SendHeartbeat(ctx context.Context) (rpc.BidiStream[Heartbeat, HeartbeatResponse], error)
	KeepConnected(ctx context.Context) (rpc.BidiStream[KeepConnectedRequest, KeepConnectedResponse], error)
	LookupVolume(ctx context.Context, in *LookupVolumeRequest) (*LookupVolumeResponse, error)
	Assign(ctx context.Context, in *AssignRequest) (*AssignResponse, error)
	StreamAssign(ctx context.Context) (rpc.BidiStream[AssignRequest, AssignResponse], error)
	Statistics(ctx context.Context, in *StatisticsRequest) (*StatisticsResponse, error)
	CollectionList(ctx context.Context, in *CollectionListRequest) (*CollectionListResponse, error)
	CollectionDelete(ctx context.Context, in *CollectionDeleteRequest) (*CollectionDeleteResponse, error)
	VolumeList(ctx context.Context, in *VolumeListRequest) (*VolumeListResponse, error)
	LookupEcVolume(ctx context.Context, in *LookupEcVolumeRequest) (*LookupEcVolumeResponse, error)
	VacuumVolume(ctx context.Context, in *VacuumVolumeRequest) (*VacuumVolumeResponse, error)
	DisableVacuum(ctx context.Context, in *DisableVacuumRequest) (*DisableVacuumResponse, error)
	EnableVacuum(ctx context.Context, in *EnableVacuumRequest) (*EnableVacuumResponse, error)
	VolumeMarkReadonly(ctx context.Context, in *VolumeMarkReadonlyRequest) (*VolumeMarkReadonlyResponse, error)
	GetMasterConfiguration(ctx context.Context, in *GetMasterConfigurationRequest) (*GetMasterConfigurationResponse, error)
	ListClusterNodes(ctx context.Context, in *ListClusterNodesRequest) (*ListClusterNodesResponse, error)
	LeaseAdminToken(ctx context.Context, in *LeaseAdminTokenRequest) (*LeaseAdminTokenResponse, error)
	ReleaseAdminToken(ctx context.Context, in *ReleaseAdminTokenRequest) (*ReleaseAdminTokenResponse, error)
	Ping(ctx context.Context, in *PingRequest) (*PingResponse, error)
	RaftListClusterServers(ctx context.Context, in *RaftListClusterServersRequest) (*RaftListClusterServersResponse, error)
	RaftAddServer(ctx context.Context, in *RaftAddServerRequest) (*RaftAddServerResponse, error)
	RaftRemoveServer(ctx context.Context, in *RaftRemoveServerRequest) (*RaftRemoveServerResponse, error)
	RaftLeadershipTransfer(ctx context.Context, in *RaftLeadershipTransferRequest) (*RaftLeadershipTransferResponse, error)
	VolumeGrow(ctx context.Context, in *VolumeGrowRequest) (*VolumeGrowResponse, error)
}

// Server-side bidi-stream seams — the grpc-free halves the master engine uses.
// Each reads requests with Recv (io.EOF on client half-close) and ships
// responses with Send; Context ends with the stream (peer disconnect included).

// Hanzo_SendHeartbeatServer is the server side of the SendHeartbeat bidi-stream.
type Hanzo_SendHeartbeatServer interface {
	Send(*HeartbeatResponse) error
	Recv() (*Heartbeat, error)
	Context() context.Context
}

// Hanzo_KeepConnectedServer is the server side of the KeepConnected bidi-stream.
type Hanzo_KeepConnectedServer interface {
	Send(*KeepConnectedResponse) error
	Recv() (*KeepConnectedRequest, error)
	Context() context.Context
}

// Hanzo_StreamAssignServer is the server side of the StreamAssign bidi-stream.
type Hanzo_StreamAssignServer interface {
	Send(*AssignResponse) error
	Recv() (*AssignRequest, error)
	Context() context.Context
}

// HanzoServer is the server API for the Hanzo (master) service: the plain method
// set the engine implements and the ZAP servers (wire + masterstream) dispatch
// to.
type HanzoServer interface {
	SendHeartbeat(Hanzo_SendHeartbeatServer) error
	KeepConnected(Hanzo_KeepConnectedServer) error
	LookupVolume(context.Context, *LookupVolumeRequest) (*LookupVolumeResponse, error)
	Assign(context.Context, *AssignRequest) (*AssignResponse, error)
	StreamAssign(Hanzo_StreamAssignServer) error
	Statistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error)
	CollectionList(context.Context, *CollectionListRequest) (*CollectionListResponse, error)
	CollectionDelete(context.Context, *CollectionDeleteRequest) (*CollectionDeleteResponse, error)
	VolumeList(context.Context, *VolumeListRequest) (*VolumeListResponse, error)
	LookupEcVolume(context.Context, *LookupEcVolumeRequest) (*LookupEcVolumeResponse, error)
	VacuumVolume(context.Context, *VacuumVolumeRequest) (*VacuumVolumeResponse, error)
	DisableVacuum(context.Context, *DisableVacuumRequest) (*DisableVacuumResponse, error)
	EnableVacuum(context.Context, *EnableVacuumRequest) (*EnableVacuumResponse, error)
	VolumeMarkReadonly(context.Context, *VolumeMarkReadonlyRequest) (*VolumeMarkReadonlyResponse, error)
	GetMasterConfiguration(context.Context, *GetMasterConfigurationRequest) (*GetMasterConfigurationResponse, error)
	ListClusterNodes(context.Context, *ListClusterNodesRequest) (*ListClusterNodesResponse, error)
	LeaseAdminToken(context.Context, *LeaseAdminTokenRequest) (*LeaseAdminTokenResponse, error)
	ReleaseAdminToken(context.Context, *ReleaseAdminTokenRequest) (*ReleaseAdminTokenResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	RaftListClusterServers(context.Context, *RaftListClusterServersRequest) (*RaftListClusterServersResponse, error)
	RaftAddServer(context.Context, *RaftAddServerRequest) (*RaftAddServerResponse, error)
	RaftRemoveServer(context.Context, *RaftRemoveServerRequest) (*RaftRemoveServerResponse, error)
	RaftLeadershipTransfer(context.Context, *RaftLeadershipTransferRequest) (*RaftLeadershipTransferResponse, error)
	VolumeGrow(context.Context, *VolumeGrowRequest) (*VolumeGrowResponse, error)
}
