// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: s3_lifecycle.proto

package s3_lifecycle_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HanzoS3LifecycleInternal_LifecycleDelete_FullMethodName = "/s3_lifecycle_pb.HanzoS3LifecycleInternal/LifecycleDelete"
)

// HanzoS3LifecycleInternalClient is the client API for HanzoS3LifecycleInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HanzoS3LifecycleInternal is the worker-to-S3 service that performs the
// actual lifecycle deletion. The lifecycle worker computes the (rule, action)
// verdict locally; the S3 server is the only component allowed to mutate the
// filer state, so it gets the final word: it re-fetches the live entry,
// verifies the EntryIdentity CAS, runs object-lock protections, and dispatches
// to the appropriate internal helper.
type HanzoS3LifecycleInternalClient interface {
	LifecycleDelete(ctx context.Context, in *LifecycleDeleteRequest, opts ...grpc.CallOption) (*LifecycleDeleteResponse, error)
}

type hanzoS3LifecycleInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewHanzoS3LifecycleInternalClient(cc grpc.ClientConnInterface) HanzoS3LifecycleInternalClient {
	return &hanzoS3LifecycleInternalClient{cc}
}

func (c *hanzoS3LifecycleInternalClient) LifecycleDelete(ctx context.Context, in *LifecycleDeleteRequest, opts ...grpc.CallOption) (*LifecycleDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifecycleDeleteResponse)
	err := c.cc.Invoke(ctx, HanzoS3LifecycleInternal_LifecycleDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HanzoS3LifecycleInternalServer is the server API for HanzoS3LifecycleInternal service.
// All implementations must embed UnimplementedHanzoS3LifecycleInternalServer
// for forward compatibility.
//
// HanzoS3LifecycleInternal is the worker-to-S3 service that performs the
// actual lifecycle deletion. The lifecycle worker computes the (rule, action)
// verdict locally; the S3 server is the only component allowed to mutate the
// filer state, so it gets the final word: it re-fetches the live entry,
// verifies the EntryIdentity CAS, runs object-lock protections, and dispatches
// to the appropriate internal helper.
type HanzoS3LifecycleInternalServer interface {
	LifecycleDelete(context.Context, *LifecycleDeleteRequest) (*LifecycleDeleteResponse, error)
	mustEmbedUnimplementedHanzoS3LifecycleInternalServer()
}

// UnimplementedHanzoS3LifecycleInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHanzoS3LifecycleInternalServer struct{}

func (UnimplementedHanzoS3LifecycleInternalServer) LifecycleDelete(context.Context, *LifecycleDeleteRequest) (*LifecycleDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LifecycleDelete not implemented")
}
func (UnimplementedHanzoS3LifecycleInternalServer) mustEmbedUnimplementedHanzoS3LifecycleInternalServer() {
}
func (UnimplementedHanzoS3LifecycleInternalServer) testEmbeddedByValue() {}

// UnsafeHanzoS3LifecycleInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HanzoS3LifecycleInternalServer will
// result in compilation errors.
type UnsafeHanzoS3LifecycleInternalServer interface {
	mustEmbedUnimplementedHanzoS3LifecycleInternalServer()
}

func RegisterHanzoS3LifecycleInternalServer(s grpc.ServiceRegistrar, srv HanzoS3LifecycleInternalServer) {
	// If the following call panics, it indicates UnimplementedHanzoS3LifecycleInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HanzoS3LifecycleInternal_ServiceDesc, srv)
}

func _HanzoS3LifecycleInternal_LifecycleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifecycleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3LifecycleInternalServer).LifecycleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3LifecycleInternal_LifecycleDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3LifecycleInternalServer).LifecycleDelete(ctx, req.(*LifecycleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HanzoS3LifecycleInternal_ServiceDesc is the grpc.ServiceDesc for HanzoS3LifecycleInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HanzoS3LifecycleInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "s3_lifecycle_pb.HanzoS3LifecycleInternal",
	HandlerType: (*HanzoS3LifecycleInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LifecycleDelete",
			Handler:    _HanzoS3LifecycleInternal_LifecycleDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s3_lifecycle.proto",
}
