// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: filer.proto
//
// gRPC ripped: this file holds only the grpc-free HanzoFiler contracts. The
// client interface returns the shared rpc.* stream seams; the server interface
// is a plain method set (no mustEmbed). The transport is github.com/zap-proto/go
// — the ZAP adapters in package filerzap satisfy these contracts and the wire
// Dispatch serves them. No grpc client/server scaffolding remains.

package filer_pb

import (
	context "context"

	"github.com/hanzoai/s3/s3/pb/rpc"
)

const (
	HanzoFiler_LookupDirectoryEntry_FullMethodName            = "/filer_pb.HanzoFiler/LookupDirectoryEntry"
	HanzoFiler_ListEntries_FullMethodName                     = "/filer_pb.HanzoFiler/ListEntries"
	HanzoFiler_CreateEntry_FullMethodName                     = "/filer_pb.HanzoFiler/CreateEntry"
	HanzoFiler_UpdateEntry_FullMethodName                     = "/filer_pb.HanzoFiler/UpdateEntry"
	HanzoFiler_TouchAccessTime_FullMethodName                 = "/filer_pb.HanzoFiler/TouchAccessTime"
	HanzoFiler_AppendToEntry_FullMethodName                   = "/filer_pb.HanzoFiler/AppendToEntry"
	HanzoFiler_DeleteEntry_FullMethodName                     = "/filer_pb.HanzoFiler/DeleteEntry"
	HanzoFiler_ObjectTransaction_FullMethodName               = "/filer_pb.HanzoFiler/ObjectTransaction"
	HanzoFiler_ObjectTransactionBatch_FullMethodName          = "/filer_pb.HanzoFiler/ObjectTransactionBatch"
	HanzoFiler_PosixLock_FullMethodName                       = "/filer_pb.HanzoFiler/PosixLock"
	HanzoFiler_AtomicRenameEntry_FullMethodName               = "/filer_pb.HanzoFiler/AtomicRenameEntry"
	HanzoFiler_StreamRenameEntry_FullMethodName               = "/filer_pb.HanzoFiler/StreamRenameEntry"
	HanzoFiler_StreamMutateEntry_FullMethodName               = "/filer_pb.HanzoFiler/StreamMutateEntry"
	HanzoFiler_AssignVolume_FullMethodName                    = "/filer_pb.HanzoFiler/AssignVolume"
	HanzoFiler_LookupVolume_FullMethodName                    = "/filer_pb.HanzoFiler/LookupVolume"
	HanzoFiler_CollectionList_FullMethodName                  = "/filer_pb.HanzoFiler/CollectionList"
	HanzoFiler_DeleteCollection_FullMethodName                = "/filer_pb.HanzoFiler/DeleteCollection"
	HanzoFiler_Statistics_FullMethodName                      = "/filer_pb.HanzoFiler/Statistics"
	HanzoFiler_Ping_FullMethodName                            = "/filer_pb.HanzoFiler/Ping"
	HanzoFiler_GetFilerConfiguration_FullMethodName           = "/filer_pb.HanzoFiler/GetFilerConfiguration"
	HanzoFiler_TraverseBfsMetadata_FullMethodName             = "/filer_pb.HanzoFiler/TraverseBfsMetadata"
	HanzoFiler_SubscribeMetadata_FullMethodName               = "/filer_pb.HanzoFiler/SubscribeMetadata"
	HanzoFiler_SubscribeLocalMetadata_FullMethodName          = "/filer_pb.HanzoFiler/SubscribeLocalMetadata"
	HanzoFiler_ListMetadataSubscribers_FullMethodName         = "/filer_pb.HanzoFiler/ListMetadataSubscribers"
	HanzoFiler_KvGet_FullMethodName                           = "/filer_pb.HanzoFiler/KvGet"
	HanzoFiler_KvPut_FullMethodName                           = "/filer_pb.HanzoFiler/KvPut"
	HanzoFiler_CacheRemoteObjectToLocalCluster_FullMethodName = "/filer_pb.HanzoFiler/CacheRemoteObjectToLocalCluster"
	HanzoFiler_DistributedLock_FullMethodName                 = "/filer_pb.HanzoFiler/DistributedLock"
	HanzoFiler_DistributedUnlock_FullMethodName               = "/filer_pb.HanzoFiler/DistributedUnlock"
	HanzoFiler_FindLockOwner_FullMethodName                   = "/filer_pb.HanzoFiler/FindLockOwner"
	HanzoFiler_TransferLocks_FullMethodName                   = "/filer_pb.HanzoFiler/TransferLocks"
	HanzoFiler_ReplicateLock_FullMethodName                   = "/filer_pb.HanzoFiler/ReplicateLock"
	HanzoFiler_MountRegister_FullMethodName                   = "/filer_pb.HanzoFiler/MountRegister"
	HanzoFiler_MountList_FullMethodName                       = "/filer_pb.HanzoFiler/MountList"
)

// HanzoFilerClient is the client API for HanzoFiler service. Unary RPCs return
// the response; streaming RPCs return an rpc.* stream seam read with Recv (and,
// for the bidi RPC, written with Send).
type HanzoFilerClient interface {
	LookupDirectoryEntry(ctx context.Context, in *LookupDirectoryEntryRequest) (*LookupDirectoryEntryResponse, error)
	ListEntries(ctx context.Context, in *ListEntriesRequest) (rpc.ServerStream[ListEntriesResponse], error)
	CreateEntry(ctx context.Context, in *CreateEntryRequest) (*CreateEntryResponse, error)
	UpdateEntry(ctx context.Context, in *UpdateEntryRequest) (*UpdateEntryResponse, error)
	TouchAccessTime(ctx context.Context, in *TouchAccessTimeRequest) (*TouchAccessTimeResponse, error)
	AppendToEntry(ctx context.Context, in *AppendToEntryRequest) (*AppendToEntryResponse, error)
	DeleteEntry(ctx context.Context, in *DeleteEntryRequest) (*DeleteEntryResponse, error)
	ObjectTransaction(ctx context.Context, in *ObjectTransactionRequest) (*ObjectTransactionResponse, error)
	ObjectTransactionBatch(ctx context.Context, in *ObjectTransactionBatchRequest) (*ObjectTransactionBatchResponse, error)
	PosixLock(ctx context.Context, in *PosixLockRequest) (*PosixLockResponse, error)
	AtomicRenameEntry(ctx context.Context, in *AtomicRenameEntryRequest) (*AtomicRenameEntryResponse, error)
	StreamRenameEntry(ctx context.Context, in *StreamRenameEntryRequest) (rpc.ServerStream[StreamRenameEntryResponse], error)
	StreamMutateEntry(ctx context.Context) (rpc.BidiStream[StreamMutateEntryRequest, StreamMutateEntryResponse], error)
	AssignVolume(ctx context.Context, in *AssignVolumeRequest) (*AssignVolumeResponse, error)
	LookupVolume(ctx context.Context, in *LookupVolumeRequest) (*LookupVolumeResponse, error)
	CollectionList(ctx context.Context, in *CollectionListRequest) (*CollectionListResponse, error)
	DeleteCollection(ctx context.Context, in *DeleteCollectionRequest) (*DeleteCollectionResponse, error)
	Statistics(ctx context.Context, in *StatisticsRequest) (*StatisticsResponse, error)
	Ping(ctx context.Context, in *PingRequest) (*PingResponse, error)
	GetFilerConfiguration(ctx context.Context, in *GetFilerConfigurationRequest) (*GetFilerConfigurationResponse, error)
	TraverseBfsMetadata(ctx context.Context, in *TraverseBfsMetadataRequest) (rpc.ServerStream[TraverseBfsMetadataResponse], error)
	SubscribeMetadata(ctx context.Context, in *SubscribeMetadataRequest) (rpc.ServerStream[SubscribeMetadataResponse], error)
	SubscribeLocalMetadata(ctx context.Context, in *SubscribeMetadataRequest) (rpc.ServerStream[SubscribeMetadataResponse], error)
	// List the metadata subscribers currently connected to this filer
	// (FUSE mounts, S3, filer.sync, peer filers, ...).
	ListMetadataSubscribers(ctx context.Context, in *ListMetadataSubscribersRequest) (*ListMetadataSubscribersResponse, error)
	KvGet(ctx context.Context, in *KvGetRequest) (*KvGetResponse, error)
	KvPut(ctx context.Context, in *KvPutRequest) (*KvPutResponse, error)
	CacheRemoteObjectToLocalCluster(ctx context.Context, in *CacheRemoteObjectToLocalClusterRequest) (*CacheRemoteObjectToLocalClusterResponse, error)
	DistributedLock(ctx context.Context, in *LockRequest) (*LockResponse, error)
	DistributedUnlock(ctx context.Context, in *UnlockRequest) (*UnlockResponse, error)
	FindLockOwner(ctx context.Context, in *FindLockOwnerRequest) (*FindLockOwnerResponse, error)
	// distributed lock management internal use only
	TransferLocks(ctx context.Context, in *TransferLocksRequest) (*TransferLocksResponse, error)
	ReplicateLock(ctx context.Context, in *ReplicateLockRequest) (*ReplicateLockResponse, error)
	// Peer chunk sharing — tier 1: mount-server registry.
	// See design-weed-mount-peer-chunk-sharing.md for details.
	MountRegister(ctx context.Context, in *MountRegisterRequest) (*MountRegisterResponse, error)
	MountList(ctx context.Context, in *MountListRequest) (*MountListResponse, error)
}

// Server-side stream seams — the grpc-free halves the filer engine uses: a
// server-streaming RPC pushes responses with Send; the bidi RPC also reads
// requests with Recv. Context ends with the stream (peer disconnect included).

// HanzoFiler_ListEntriesServer is the server side of the ListEntries server-stream.
type HanzoFiler_ListEntriesServer interface {
	Send(*ListEntriesResponse) error
	Context() context.Context
}

// HanzoFiler_StreamRenameEntryServer is the server side of the StreamRenameEntry server-stream.
type HanzoFiler_StreamRenameEntryServer interface {
	Send(*StreamRenameEntryResponse) error
	Context() context.Context
}

// HanzoFiler_TraverseBfsMetadataServer is the server side of the TraverseBfsMetadata server-stream.
type HanzoFiler_TraverseBfsMetadataServer interface {
	Send(*TraverseBfsMetadataResponse) error
	Context() context.Context
}

// HanzoFiler_SubscribeMetadataServer is the server side of the SubscribeMetadata server-stream.
type HanzoFiler_SubscribeMetadataServer interface {
	Send(*SubscribeMetadataResponse) error
	Context() context.Context
}

// HanzoFiler_SubscribeLocalMetadataServer is the server side of the SubscribeLocalMetadata server-stream.
type HanzoFiler_SubscribeLocalMetadataServer interface {
	Send(*SubscribeMetadataResponse) error
	Context() context.Context
}

// HanzoFiler_StreamMutateEntryServer is the server side of the StreamMutateEntry bidi-stream.
type HanzoFiler_StreamMutateEntryServer interface {
	Send(*StreamMutateEntryResponse) error
	Recv() (*StreamMutateEntryRequest, error)
	Context() context.Context
}

// HanzoFilerServer is the server API for HanzoFiler service: the plain method
// set the engine implements and the ZAP server backend dispatches to.
type HanzoFilerServer interface {
	LookupDirectoryEntry(context.Context, *LookupDirectoryEntryRequest) (*LookupDirectoryEntryResponse, error)
	ListEntries(*ListEntriesRequest, HanzoFiler_ListEntriesServer) error
	CreateEntry(context.Context, *CreateEntryRequest) (*CreateEntryResponse, error)
	UpdateEntry(context.Context, *UpdateEntryRequest) (*UpdateEntryResponse, error)
	TouchAccessTime(context.Context, *TouchAccessTimeRequest) (*TouchAccessTimeResponse, error)
	AppendToEntry(context.Context, *AppendToEntryRequest) (*AppendToEntryResponse, error)
	DeleteEntry(context.Context, *DeleteEntryRequest) (*DeleteEntryResponse, error)
	ObjectTransaction(context.Context, *ObjectTransactionRequest) (*ObjectTransactionResponse, error)
	ObjectTransactionBatch(context.Context, *ObjectTransactionBatchRequest) (*ObjectTransactionBatchResponse, error)
	PosixLock(context.Context, *PosixLockRequest) (*PosixLockResponse, error)
	AtomicRenameEntry(context.Context, *AtomicRenameEntryRequest) (*AtomicRenameEntryResponse, error)
	StreamRenameEntry(*StreamRenameEntryRequest, HanzoFiler_StreamRenameEntryServer) error
	StreamMutateEntry(HanzoFiler_StreamMutateEntryServer) error
	AssignVolume(context.Context, *AssignVolumeRequest) (*AssignVolumeResponse, error)
	LookupVolume(context.Context, *LookupVolumeRequest) (*LookupVolumeResponse, error)
	CollectionList(context.Context, *CollectionListRequest) (*CollectionListResponse, error)
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error)
	Statistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetFilerConfiguration(context.Context, *GetFilerConfigurationRequest) (*GetFilerConfigurationResponse, error)
	TraverseBfsMetadata(*TraverseBfsMetadataRequest, HanzoFiler_TraverseBfsMetadataServer) error
	SubscribeMetadata(*SubscribeMetadataRequest, HanzoFiler_SubscribeMetadataServer) error
	SubscribeLocalMetadata(*SubscribeMetadataRequest, HanzoFiler_SubscribeLocalMetadataServer) error
	// List the metadata subscribers currently connected to this filer
	// (FUSE mounts, S3, filer.sync, peer filers, ...).
	ListMetadataSubscribers(context.Context, *ListMetadataSubscribersRequest) (*ListMetadataSubscribersResponse, error)
	KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error)
	KvPut(context.Context, *KvPutRequest) (*KvPutResponse, error)
	CacheRemoteObjectToLocalCluster(context.Context, *CacheRemoteObjectToLocalClusterRequest) (*CacheRemoteObjectToLocalClusterResponse, error)
	DistributedLock(context.Context, *LockRequest) (*LockResponse, error)
	DistributedUnlock(context.Context, *UnlockRequest) (*UnlockResponse, error)
	FindLockOwner(context.Context, *FindLockOwnerRequest) (*FindLockOwnerResponse, error)
	// distributed lock management internal use only
	TransferLocks(context.Context, *TransferLocksRequest) (*TransferLocksResponse, error)
	ReplicateLock(context.Context, *ReplicateLockRequest) (*ReplicateLockResponse, error)
	// Peer chunk sharing — tier 1: mount-server registry.
	// See design-weed-mount-peer-chunk-sharing.md for details.
	MountRegister(context.Context, *MountRegisterRequest) (*MountRegisterResponse, error)
	MountList(context.Context, *MountListRequest) (*MountListResponse, error)
}
