// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: iam.proto
//
// gRPC cut out: the IAM service rides the ZAP transport (see s3/wire/iam), so
// the client/server scaffolding has been removed. Only the typed method-set
// interfaces survive — the transport-free client (no per-call options) and the
// plain server contract — for any consumer that wants the iam_pb shapes without
// the RPC runtime.

package iam_pb

import (
	context "context"
)

// HanzoIdentityAccessManagementClient is the client API for HanzoIdentityAccessManagement service.
type HanzoIdentityAccessManagementClient interface {
	// Configuration Management
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest) (*GetConfigurationResponse, error)
	PutConfiguration(ctx context.Context, in *PutConfigurationRequest) (*PutConfigurationResponse, error)
	// User Management
	CreateUser(ctx context.Context, in *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest) (*DeleteUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest) (*ListUsersResponse, error)
	// Access Key Management
	CreateAccessKey(ctx context.Context, in *CreateAccessKeyRequest) (*CreateAccessKeyResponse, error)
	DeleteAccessKey(ctx context.Context, in *DeleteAccessKeyRequest) (*DeleteAccessKeyResponse, error)
	GetUserByAccessKey(ctx context.Context, in *GetUserByAccessKeyRequest) (*GetUserByAccessKeyResponse, error)
	// Policy Management
	PutPolicy(ctx context.Context, in *PutPolicyRequest) (*PutPolicyResponse, error)
	GetPolicy(ctx context.Context, in *GetPolicyRequest) (*GetPolicyResponse, error)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest) (*ListPoliciesResponse, error)
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest) (*DeletePolicyResponse, error)
	// Service Account Management
	CreateServiceAccount(ctx context.Context, in *CreateServiceAccountRequest) (*CreateServiceAccountResponse, error)
	UpdateServiceAccount(ctx context.Context, in *UpdateServiceAccountRequest) (*UpdateServiceAccountResponse, error)
	DeleteServiceAccount(ctx context.Context, in *DeleteServiceAccountRequest) (*DeleteServiceAccountResponse, error)
	GetServiceAccount(ctx context.Context, in *GetServiceAccountRequest) (*GetServiceAccountResponse, error)
	ListServiceAccounts(ctx context.Context, in *ListServiceAccountsRequest) (*ListServiceAccountsResponse, error)
	GetServiceAccountByAccessKey(ctx context.Context, in *GetServiceAccountByAccessKeyRequest) (*GetServiceAccountByAccessKeyResponse, error)
}

// HanzoIdentityAccessManagementServer is the server API for HanzoIdentityAccessManagement service.
type HanzoIdentityAccessManagementServer interface {
	// Configuration Management
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	PutConfiguration(context.Context, *PutConfigurationRequest) (*PutConfigurationResponse, error)
	// User Management
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// Access Key Management
	CreateAccessKey(context.Context, *CreateAccessKeyRequest) (*CreateAccessKeyResponse, error)
	DeleteAccessKey(context.Context, *DeleteAccessKeyRequest) (*DeleteAccessKeyResponse, error)
	GetUserByAccessKey(context.Context, *GetUserByAccessKeyRequest) (*GetUserByAccessKeyResponse, error)
	// Policy Management
	PutPolicy(context.Context, *PutPolicyRequest) (*PutPolicyResponse, error)
	GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error)
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error)
	// Service Account Management
	CreateServiceAccount(context.Context, *CreateServiceAccountRequest) (*CreateServiceAccountResponse, error)
	UpdateServiceAccount(context.Context, *UpdateServiceAccountRequest) (*UpdateServiceAccountResponse, error)
	DeleteServiceAccount(context.Context, *DeleteServiceAccountRequest) (*DeleteServiceAccountResponse, error)
	GetServiceAccount(context.Context, *GetServiceAccountRequest) (*GetServiceAccountResponse, error)
	ListServiceAccounts(context.Context, *ListServiceAccountsRequest) (*ListServiceAccountsResponse, error)
	GetServiceAccountByAccessKey(context.Context, *GetServiceAccountByAccessKeyRequest) (*GetServiceAccountByAccessKeyResponse, error)
}
