FROM chrislusf/rocksdb_dev_env as builder

# build Hanzo
RUN mkdir -p /go/src/github.com/hanzo/
ADD . /go/src/github.com/hanzoai/s3
RUN ls -al /go/src/github.com/hanzo/ && \
  cd /go/src/github.com/hanzoai/s3/s3 \
  && export LDFLAGS="-X github.com/hanzoai/s3/s3/util/version.COMMIT=$(git rev-parse --short HEAD)" \
  && go install -tags "5BytesOffset rocksdb" -ldflags "-extldflags -static ${LDFLAGS}"


FROM alpine AS final
LABEL author="Chris Lu"
COPY --from=builder /go/bin/s3 /usr/bin/
RUN mkdir -p /etc/hanzo
COPY --from=builder /go/src/github.com/hanzoai/s3/docker/filer_rocksdb.toml /etc/hanzo/filer.toml
COPY --from=builder /go/src/github.com/hanzoai/s3/docker/entrypoint.sh /entrypoint.sh

# Install dependencies and create non-root user
RUN apk upgrade --no-cache && \
    apk add --no-cache fuse snappy gflags curl tmux su-exec && \
    addgroup -g 1000 hanzo && \
    adduser -D -u 1000 -G hanzo hanzo

# volume server gprc port
EXPOSE 18080
# volume server http port
EXPOSE 8080
# filer server gprc port
EXPOSE 18888
# filer server http port
EXPOSE 8888
# master server shared gprc port
EXPOSE 19333
# master server shared http port
EXPOSE 9333
# s3 server http port
EXPOSE 8333
# webdav server http port
EXPOSE 7333

# Create data directory and set proper ownership for hanzo user
RUN mkdir -p /data/filer_rocksdb && \
    chown -R hanzo:hanzo /data && \
    chown -R hanzo:hanzo /etc/hanzo && \
    chmod 755 /entrypoint.sh

VOLUME /data

WORKDIR /data

# Entrypoint will handle permission fixes and user switching
ENTRYPOINT ["/entrypoint.sh"]
