// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: mq_broker.proto
//
// gRPC ripped: this file holds only the grpc-free HanzoMessaging contracts. The
// client interface returns the shared rpc.* stream seams; the server interface
// is a plain method set (no mustEmbed). The transport is github.com/zap-proto/go
// — the ZAP adapters in package mqzap satisfy these contracts and the wire
// Dispatch serves them. No grpc client/server scaffolding remains.

package mq_pb

import (
	context "context"
	errors "errors"

	"github.com/hanzoai/s3/s3/pb/rpc"
)

const (
	HanzoMessaging_FindBrokerLeader_FullMethodName           = "/messaging_pb.HanzoMessaging/FindBrokerLeader"
	HanzoMessaging_PublisherToPubBalancer_FullMethodName     = "/messaging_pb.HanzoMessaging/PublisherToPubBalancer"
	HanzoMessaging_BalanceTopics_FullMethodName              = "/messaging_pb.HanzoMessaging/BalanceTopics"
	HanzoMessaging_ListTopics_FullMethodName                 = "/messaging_pb.HanzoMessaging/ListTopics"
	HanzoMessaging_TopicExists_FullMethodName                = "/messaging_pb.HanzoMessaging/TopicExists"
	HanzoMessaging_ConfigureTopic_FullMethodName             = "/messaging_pb.HanzoMessaging/ConfigureTopic"
	HanzoMessaging_LookupTopicBrokers_FullMethodName         = "/messaging_pb.HanzoMessaging/LookupTopicBrokers"
	HanzoMessaging_GetTopicConfiguration_FullMethodName      = "/messaging_pb.HanzoMessaging/GetTopicConfiguration"
	HanzoMessaging_GetTopicPublishers_FullMethodName         = "/messaging_pb.HanzoMessaging/GetTopicPublishers"
	HanzoMessaging_GetTopicSubscribers_FullMethodName        = "/messaging_pb.HanzoMessaging/GetTopicSubscribers"
	HanzoMessaging_AssignTopicPartitions_FullMethodName      = "/messaging_pb.HanzoMessaging/AssignTopicPartitions"
	HanzoMessaging_ClosePublishers_FullMethodName            = "/messaging_pb.HanzoMessaging/ClosePublishers"
	HanzoMessaging_CloseSubscribers_FullMethodName           = "/messaging_pb.HanzoMessaging/CloseSubscribers"
	HanzoMessaging_SubscriberToSubCoordinator_FullMethodName = "/messaging_pb.HanzoMessaging/SubscriberToSubCoordinator"
	HanzoMessaging_PublishMessage_FullMethodName             = "/messaging_pb.HanzoMessaging/PublishMessage"
	HanzoMessaging_SubscribeMessage_FullMethodName           = "/messaging_pb.HanzoMessaging/SubscribeMessage"
	HanzoMessaging_PublishFollowMe_FullMethodName            = "/messaging_pb.HanzoMessaging/PublishFollowMe"
	HanzoMessaging_SubscribeFollowMe_FullMethodName          = "/messaging_pb.HanzoMessaging/SubscribeFollowMe"
	HanzoMessaging_FetchMessage_FullMethodName               = "/messaging_pb.HanzoMessaging/FetchMessage"
	HanzoMessaging_GetUnflushedMessages_FullMethodName       = "/messaging_pb.HanzoMessaging/GetUnflushedMessages"
	HanzoMessaging_GetPartitionRangeInfo_FullMethodName      = "/messaging_pb.HanzoMessaging/GetPartitionRangeInfo"
)

// HanzoMessagingClient is the client API for HanzoMessaging service. Unary RPCs
// return the response; streaming RPCs return an rpc.* stream seam: bidi RPCs
// read with Recv and write with Send, the server-streaming RPC reads with Recv,
// the client-streaming RPC writes with Send then CloseAndRecv.
type HanzoMessagingClient interface {
	// control plane
	FindBrokerLeader(ctx context.Context, in *FindBrokerLeaderRequest) (*FindBrokerLeaderResponse, error)
	// control plane for balancer
	PublisherToPubBalancer(ctx context.Context) (rpc.BidiStream[PublisherToPubBalancerRequest, PublisherToPubBalancerResponse], error)
	BalanceTopics(ctx context.Context, in *BalanceTopicsRequest) (*BalanceTopicsResponse, error)
	// control plane for topic partitions
	ListTopics(ctx context.Context, in *ListTopicsRequest) (*ListTopicsResponse, error)
	TopicExists(ctx context.Context, in *TopicExistsRequest) (*TopicExistsResponse, error)
	ConfigureTopic(ctx context.Context, in *ConfigureTopicRequest) (*ConfigureTopicResponse, error)
	LookupTopicBrokers(ctx context.Context, in *LookupTopicBrokersRequest) (*LookupTopicBrokersResponse, error)
	GetTopicConfiguration(ctx context.Context, in *GetTopicConfigurationRequest) (*GetTopicConfigurationResponse, error)
	GetTopicPublishers(ctx context.Context, in *GetTopicPublishersRequest) (*GetTopicPublishersResponse, error)
	GetTopicSubscribers(ctx context.Context, in *GetTopicSubscribersRequest) (*GetTopicSubscribersResponse, error)
	// invoked by the balancer, running on each broker
	AssignTopicPartitions(ctx context.Context, in *AssignTopicPartitionsRequest) (*AssignTopicPartitionsResponse, error)
	ClosePublishers(ctx context.Context, in *ClosePublishersRequest) (*ClosePublishersResponse, error)
	CloseSubscribers(ctx context.Context, in *CloseSubscribersRequest) (*CloseSubscribersResponse, error)
	// subscriber connects to broker balancer, which coordinates with the subscribers
	SubscriberToSubCoordinator(ctx context.Context) (rpc.BidiStream[SubscriberToSubCoordinatorRequest, SubscriberToSubCoordinatorResponse], error)
	// data plane for each topic partition
	PublishMessage(ctx context.Context) (rpc.BidiStream[PublishMessageRequest, PublishMessageResponse], error)
	SubscribeMessage(ctx context.Context) (rpc.BidiStream[SubscribeMessageRequest, SubscribeMessageResponse], error)
	// The lead broker asks a follower broker to follow itself
	PublishFollowMe(ctx context.Context) (rpc.BidiStream[PublishFollowMeRequest, PublishFollowMeResponse], error)
	SubscribeFollowMe(ctx context.Context) (rpc.ClientStream[SubscribeFollowMeRequest, SubscribeFollowMeResponse], error)
	// Stateless fetch API (Kafka-style) - request/response pattern
	// This is the recommended API for Kafka gateway and other stateless clients
	// No streaming, no session state - each request is completely independent
	FetchMessage(ctx context.Context, in *FetchMessageRequest) (*FetchMessageResponse, error)
	// SQL query support - get unflushed messages from broker's in-memory buffer (streaming)
	GetUnflushedMessages(ctx context.Context, in *GetUnflushedMessagesRequest) (rpc.ServerStream[GetUnflushedMessagesResponse], error)
	// Get comprehensive partition range information (offsets, timestamps, and other fields)
	GetPartitionRangeInfo(ctx context.Context, in *GetPartitionRangeInfoRequest) (*GetPartitionRangeInfoResponse, error)
}

// Client-side stream seams — the grpc-free names existing callers reference.

// HanzoMessaging_PublisherToPubBalancerClient is the client side of the PublisherToPubBalancer bidi-stream.
type HanzoMessaging_PublisherToPubBalancerClient = rpc.BidiStream[PublisherToPubBalancerRequest, PublisherToPubBalancerResponse]

// HanzoMessaging_SubscriberToSubCoordinatorClient is the client side of the SubscriberToSubCoordinator bidi-stream.
type HanzoMessaging_SubscriberToSubCoordinatorClient = rpc.BidiStream[SubscriberToSubCoordinatorRequest, SubscriberToSubCoordinatorResponse]

// HanzoMessaging_PublishMessageClient is the client side of the PublishMessage bidi-stream.
type HanzoMessaging_PublishMessageClient = rpc.BidiStream[PublishMessageRequest, PublishMessageResponse]

// HanzoMessaging_SubscribeMessageClient is the client side of the SubscribeMessage bidi-stream.
type HanzoMessaging_SubscribeMessageClient = rpc.BidiStream[SubscribeMessageRequest, SubscribeMessageResponse]

// HanzoMessaging_PublishFollowMeClient is the client side of the PublishFollowMe bidi-stream.
type HanzoMessaging_PublishFollowMeClient = rpc.BidiStream[PublishFollowMeRequest, PublishFollowMeResponse]

// HanzoMessaging_SubscribeFollowMeClient is the client side of the SubscribeFollowMe client-stream.
type HanzoMessaging_SubscribeFollowMeClient = rpc.ClientStream[SubscribeFollowMeRequest, SubscribeFollowMeResponse]

// HanzoMessaging_GetUnflushedMessagesClient is the client side of the GetUnflushedMessages server-stream.
type HanzoMessaging_GetUnflushedMessagesClient = rpc.ServerStream[GetUnflushedMessagesResponse]

// Server-side stream seams — the grpc-free halves the broker engine uses: a bidi
// RPC reads requests with Recv and pushes responses with Send; the client-stream
// RPC reads with Recv then replies once with SendAndClose; the server-stream RPC
// pushes items with Send. Context ends with the stream (peer disconnect included).

// HanzoMessaging_PublisherToPubBalancerServer is the server side of the PublisherToPubBalancer bidi-stream.
type HanzoMessaging_PublisherToPubBalancerServer interface {
	Send(*PublisherToPubBalancerResponse) error
	Recv() (*PublisherToPubBalancerRequest, error)
	Context() context.Context
}

// HanzoMessaging_SubscriberToSubCoordinatorServer is the server side of the SubscriberToSubCoordinator bidi-stream.
type HanzoMessaging_SubscriberToSubCoordinatorServer interface {
	Send(*SubscriberToSubCoordinatorResponse) error
	Recv() (*SubscriberToSubCoordinatorRequest, error)
	Context() context.Context
}

// HanzoMessaging_PublishMessageServer is the server side of the PublishMessage bidi-stream.
type HanzoMessaging_PublishMessageServer interface {
	Send(*PublishMessageResponse) error
	Recv() (*PublishMessageRequest, error)
	Context() context.Context
}

// HanzoMessaging_SubscribeMessageServer is the server side of the SubscribeMessage bidi-stream.
type HanzoMessaging_SubscribeMessageServer interface {
	Send(*SubscribeMessageResponse) error
	Recv() (*SubscribeMessageRequest, error)
	Context() context.Context
}

// HanzoMessaging_PublishFollowMeServer is the server side of the PublishFollowMe bidi-stream.
type HanzoMessaging_PublishFollowMeServer interface {
	Send(*PublishFollowMeResponse) error
	Recv() (*PublishFollowMeRequest, error)
	Context() context.Context
}

// HanzoMessaging_SubscribeFollowMeServer is the server side of the SubscribeFollowMe client-stream.
type HanzoMessaging_SubscribeFollowMeServer interface {
	SendAndClose(*SubscribeFollowMeResponse) error
	Recv() (*SubscribeFollowMeRequest, error)
	Context() context.Context
}

// HanzoMessaging_GetUnflushedMessagesServer is the server side of the GetUnflushedMessages server-stream.
type HanzoMessaging_GetUnflushedMessagesServer interface {
	Send(*GetUnflushedMessagesResponse) error
	Context() context.Context
}

// HanzoMessagingServer is the server API for HanzoMessaging service: the plain
// method set the broker engine implements and the ZAP server backend dispatches to.
type HanzoMessagingServer interface {
	// control plane
	FindBrokerLeader(context.Context, *FindBrokerLeaderRequest) (*FindBrokerLeaderResponse, error)
	// control plane for balancer
	PublisherToPubBalancer(HanzoMessaging_PublisherToPubBalancerServer) error
	BalanceTopics(context.Context, *BalanceTopicsRequest) (*BalanceTopicsResponse, error)
	// control plane for topic partitions
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	TopicExists(context.Context, *TopicExistsRequest) (*TopicExistsResponse, error)
	ConfigureTopic(context.Context, *ConfigureTopicRequest) (*ConfigureTopicResponse, error)
	LookupTopicBrokers(context.Context, *LookupTopicBrokersRequest) (*LookupTopicBrokersResponse, error)
	GetTopicConfiguration(context.Context, *GetTopicConfigurationRequest) (*GetTopicConfigurationResponse, error)
	GetTopicPublishers(context.Context, *GetTopicPublishersRequest) (*GetTopicPublishersResponse, error)
	GetTopicSubscribers(context.Context, *GetTopicSubscribersRequest) (*GetTopicSubscribersResponse, error)
	// invoked by the balancer, running on each broker
	AssignTopicPartitions(context.Context, *AssignTopicPartitionsRequest) (*AssignTopicPartitionsResponse, error)
	ClosePublishers(context.Context, *ClosePublishersRequest) (*ClosePublishersResponse, error)
	CloseSubscribers(context.Context, *CloseSubscribersRequest) (*CloseSubscribersResponse, error)
	// subscriber connects to broker balancer, which coordinates with the subscribers
	SubscriberToSubCoordinator(HanzoMessaging_SubscriberToSubCoordinatorServer) error
	// data plane for each topic partition
	PublishMessage(HanzoMessaging_PublishMessageServer) error
	SubscribeMessage(HanzoMessaging_SubscribeMessageServer) error
	// The lead broker asks a follower broker to follow itself
	PublishFollowMe(HanzoMessaging_PublishFollowMeServer) error
	SubscribeFollowMe(HanzoMessaging_SubscribeFollowMeServer) error
	// Stateless fetch API (Kafka-style) - request/response pattern
	// This is the recommended API for Kafka gateway and other stateless clients
	// No streaming, no session state - each request is completely independent
	FetchMessage(context.Context, *FetchMessageRequest) (*FetchMessageResponse, error)
	// SQL query support - get unflushed messages from broker's in-memory buffer (streaming)
	GetUnflushedMessages(*GetUnflushedMessagesRequest, HanzoMessaging_GetUnflushedMessagesServer) error
	// Get comprehensive partition range information (offsets, timestamps, and other fields)
	GetPartitionRangeInfo(context.Context, *GetPartitionRangeInfoRequest) (*GetPartitionRangeInfoResponse, error)
}

// errUnimplemented is returned by every UnimplementedHanzoMessagingServer method.
// The de-grpc'd analogue of the generated mustEmbedUnimplemented machinery: a
// plain error, not status.Errorf(codes.Unimplemented, ...).
var errUnimplemented = errors.New("mq_pb: method not implemented")

// UnimplementedHanzoMessagingServer is a no-op HanzoMessagingServer whose every
// method returns errUnimplemented. Embed it in a partial implementation (e.g. a
// test fake that exercises only a few RPCs) to stay a total HanzoMessagingServer
// — the de-grpc'd analogue of the generated mustEmbedUnimplemented embed. The
// live broker implements every method and does NOT embed it.
type UnimplementedHanzoMessagingServer struct{}

func (UnimplementedHanzoMessagingServer) FindBrokerLeader(context.Context, *FindBrokerLeaderRequest) (*FindBrokerLeaderResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) PublisherToPubBalancer(HanzoMessaging_PublisherToPubBalancerServer) error {
	return errUnimplemented
}
func (UnimplementedHanzoMessagingServer) BalanceTopics(context.Context, *BalanceTopicsRequest) (*BalanceTopicsResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) TopicExists(context.Context, *TopicExistsRequest) (*TopicExistsResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) ConfigureTopic(context.Context, *ConfigureTopicRequest) (*ConfigureTopicResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) LookupTopicBrokers(context.Context, *LookupTopicBrokersRequest) (*LookupTopicBrokersResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) GetTopicConfiguration(context.Context, *GetTopicConfigurationRequest) (*GetTopicConfigurationResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) GetTopicPublishers(context.Context, *GetTopicPublishersRequest) (*GetTopicPublishersResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) GetTopicSubscribers(context.Context, *GetTopicSubscribersRequest) (*GetTopicSubscribersResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) AssignTopicPartitions(context.Context, *AssignTopicPartitionsRequest) (*AssignTopicPartitionsResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) ClosePublishers(context.Context, *ClosePublishersRequest) (*ClosePublishersResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) CloseSubscribers(context.Context, *CloseSubscribersRequest) (*CloseSubscribersResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) SubscriberToSubCoordinator(HanzoMessaging_SubscriberToSubCoordinatorServer) error {
	return errUnimplemented
}
func (UnimplementedHanzoMessagingServer) PublishMessage(HanzoMessaging_PublishMessageServer) error {
	return errUnimplemented
}
func (UnimplementedHanzoMessagingServer) SubscribeMessage(HanzoMessaging_SubscribeMessageServer) error {
	return errUnimplemented
}
func (UnimplementedHanzoMessagingServer) PublishFollowMe(HanzoMessaging_PublishFollowMeServer) error {
	return errUnimplemented
}
func (UnimplementedHanzoMessagingServer) SubscribeFollowMe(HanzoMessaging_SubscribeFollowMeServer) error {
	return errUnimplemented
}
func (UnimplementedHanzoMessagingServer) FetchMessage(context.Context, *FetchMessageRequest) (*FetchMessageResponse, error) {
	return nil, errUnimplemented
}
func (UnimplementedHanzoMessagingServer) GetUnflushedMessages(*GetUnflushedMessagesRequest, HanzoMessaging_GetUnflushedMessagesServer) error {
	return errUnimplemented
}
func (UnimplementedHanzoMessagingServer) GetPartitionRangeInfo(context.Context, *GetPartitionRangeInfoRequest) (*GetPartitionRangeInfoResponse, error) {
	return nil, errUnimplemented
}
