// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: s3.proto

package s3_pb

import (
	context "context"
	iam_pb "github.com/hanzoai/s3/s3/pb/iam_pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HanzoS3IamCache_PutIdentity_FullMethodName    = "/messaging_pb.HanzoS3IamCache/PutIdentity"
	HanzoS3IamCache_RemoveIdentity_FullMethodName = "/messaging_pb.HanzoS3IamCache/RemoveIdentity"
	HanzoS3IamCache_PutPolicy_FullMethodName      = "/messaging_pb.HanzoS3IamCache/PutPolicy"
	HanzoS3IamCache_GetPolicy_FullMethodName      = "/messaging_pb.HanzoS3IamCache/GetPolicy"
	HanzoS3IamCache_ListPolicies_FullMethodName   = "/messaging_pb.HanzoS3IamCache/ListPolicies"
	HanzoS3IamCache_DeletePolicy_FullMethodName   = "/messaging_pb.HanzoS3IamCache/DeletePolicy"
	HanzoS3IamCache_PutGroup_FullMethodName       = "/messaging_pb.HanzoS3IamCache/PutGroup"
	HanzoS3IamCache_RemoveGroup_FullMethodName    = "/messaging_pb.HanzoS3IamCache/RemoveGroup"
)

// HanzoS3IamCacheClient is the client API for HanzoS3IamCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Designed for unidirectional propagation from Filer to S3 Servers
type HanzoS3IamCacheClient interface {
	PutIdentity(ctx context.Context, in *iam_pb.PutIdentityRequest, opts ...grpc.CallOption) (*iam_pb.PutIdentityResponse, error)
	RemoveIdentity(ctx context.Context, in *iam_pb.RemoveIdentityRequest, opts ...grpc.CallOption) (*iam_pb.RemoveIdentityResponse, error)
	PutPolicy(ctx context.Context, in *iam_pb.PutPolicyRequest, opts ...grpc.CallOption) (*iam_pb.PutPolicyResponse, error)
	GetPolicy(ctx context.Context, in *iam_pb.GetPolicyRequest, opts ...grpc.CallOption) (*iam_pb.GetPolicyResponse, error)
	ListPolicies(ctx context.Context, in *iam_pb.ListPoliciesRequest, opts ...grpc.CallOption) (*iam_pb.ListPoliciesResponse, error)
	DeletePolicy(ctx context.Context, in *iam_pb.DeletePolicyRequest, opts ...grpc.CallOption) (*iam_pb.DeletePolicyResponse, error)
	PutGroup(ctx context.Context, in *iam_pb.PutGroupRequest, opts ...grpc.CallOption) (*iam_pb.PutGroupResponse, error)
	RemoveGroup(ctx context.Context, in *iam_pb.RemoveGroupRequest, opts ...grpc.CallOption) (*iam_pb.RemoveGroupResponse, error)
}

type hanzoS3IamCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewHanzoS3IamCacheClient(cc grpc.ClientConnInterface) HanzoS3IamCacheClient {
	return &hanzoS3IamCacheClient{cc}
}

func (c *hanzoS3IamCacheClient) PutIdentity(ctx context.Context, in *iam_pb.PutIdentityRequest, opts ...grpc.CallOption) (*iam_pb.PutIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.PutIdentityResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_PutIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoS3IamCacheClient) RemoveIdentity(ctx context.Context, in *iam_pb.RemoveIdentityRequest, opts ...grpc.CallOption) (*iam_pb.RemoveIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.RemoveIdentityResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_RemoveIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoS3IamCacheClient) PutPolicy(ctx context.Context, in *iam_pb.PutPolicyRequest, opts ...grpc.CallOption) (*iam_pb.PutPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.PutPolicyResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_PutPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoS3IamCacheClient) GetPolicy(ctx context.Context, in *iam_pb.GetPolicyRequest, opts ...grpc.CallOption) (*iam_pb.GetPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.GetPolicyResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoS3IamCacheClient) ListPolicies(ctx context.Context, in *iam_pb.ListPoliciesRequest, opts ...grpc.CallOption) (*iam_pb.ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.ListPoliciesResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoS3IamCacheClient) DeletePolicy(ctx context.Context, in *iam_pb.DeletePolicyRequest, opts ...grpc.CallOption) (*iam_pb.DeletePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.DeletePolicyResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoS3IamCacheClient) PutGroup(ctx context.Context, in *iam_pb.PutGroupRequest, opts ...grpc.CallOption) (*iam_pb.PutGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.PutGroupResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_PutGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoS3IamCacheClient) RemoveGroup(ctx context.Context, in *iam_pb.RemoveGroupRequest, opts ...grpc.CallOption) (*iam_pb.RemoveGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(iam_pb.RemoveGroupResponse)
	err := c.cc.Invoke(ctx, HanzoS3IamCache_RemoveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HanzoS3IamCacheServer is the server API for HanzoS3IamCache service.
// All implementations must embed UnimplementedHanzoS3IamCacheServer
// for forward compatibility.
//
// Designed for unidirectional propagation from Filer to S3 Servers
type HanzoS3IamCacheServer interface {
	PutIdentity(context.Context, *iam_pb.PutIdentityRequest) (*iam_pb.PutIdentityResponse, error)
	RemoveIdentity(context.Context, *iam_pb.RemoveIdentityRequest) (*iam_pb.RemoveIdentityResponse, error)
	PutPolicy(context.Context, *iam_pb.PutPolicyRequest) (*iam_pb.PutPolicyResponse, error)
	GetPolicy(context.Context, *iam_pb.GetPolicyRequest) (*iam_pb.GetPolicyResponse, error)
	ListPolicies(context.Context, *iam_pb.ListPoliciesRequest) (*iam_pb.ListPoliciesResponse, error)
	DeletePolicy(context.Context, *iam_pb.DeletePolicyRequest) (*iam_pb.DeletePolicyResponse, error)
	PutGroup(context.Context, *iam_pb.PutGroupRequest) (*iam_pb.PutGroupResponse, error)
	RemoveGroup(context.Context, *iam_pb.RemoveGroupRequest) (*iam_pb.RemoveGroupResponse, error)
	mustEmbedUnimplementedHanzoS3IamCacheServer()
}

// UnimplementedHanzoS3IamCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHanzoS3IamCacheServer struct{}

func (UnimplementedHanzoS3IamCacheServer) PutIdentity(context.Context, *iam_pb.PutIdentityRequest) (*iam_pb.PutIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutIdentity not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) RemoveIdentity(context.Context, *iam_pb.RemoveIdentityRequest) (*iam_pb.RemoveIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIdentity not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) PutPolicy(context.Context, *iam_pb.PutPolicyRequest) (*iam_pb.PutPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutPolicy not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) GetPolicy(context.Context, *iam_pb.GetPolicyRequest) (*iam_pb.GetPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) ListPolicies(context.Context, *iam_pb.ListPoliciesRequest) (*iam_pb.ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) DeletePolicy(context.Context, *iam_pb.DeletePolicyRequest) (*iam_pb.DeletePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) PutGroup(context.Context, *iam_pb.PutGroupRequest) (*iam_pb.PutGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutGroup not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) RemoveGroup(context.Context, *iam_pb.RemoveGroupRequest) (*iam_pb.RemoveGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGroup not implemented")
}
func (UnimplementedHanzoS3IamCacheServer) mustEmbedUnimplementedHanzoS3IamCacheServer() {}
func (UnimplementedHanzoS3IamCacheServer) testEmbeddedByValue()                         {}

// UnsafeHanzoS3IamCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HanzoS3IamCacheServer will
// result in compilation errors.
type UnsafeHanzoS3IamCacheServer interface {
	mustEmbedUnimplementedHanzoS3IamCacheServer()
}

func RegisterHanzoS3IamCacheServer(s grpc.ServiceRegistrar, srv HanzoS3IamCacheServer) {
	// If the following call panics, it indicates UnimplementedHanzoS3IamCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HanzoS3IamCache_ServiceDesc, srv)
}

func _HanzoS3IamCache_PutIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.PutIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).PutIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_PutIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).PutIdentity(ctx, req.(*iam_pb.PutIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoS3IamCache_RemoveIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.RemoveIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).RemoveIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_RemoveIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).RemoveIdentity(ctx, req.(*iam_pb.RemoveIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoS3IamCache_PutPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.PutPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).PutPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_PutPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).PutPolicy(ctx, req.(*iam_pb.PutPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoS3IamCache_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).GetPolicy(ctx, req.(*iam_pb.GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoS3IamCache_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).ListPolicies(ctx, req.(*iam_pb.ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoS3IamCache_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).DeletePolicy(ctx, req.(*iam_pb.DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoS3IamCache_PutGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.PutGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).PutGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_PutGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).PutGroup(ctx, req.(*iam_pb.PutGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoS3IamCache_RemoveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(iam_pb.RemoveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoS3IamCacheServer).RemoveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoS3IamCache_RemoveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoS3IamCacheServer).RemoveGroup(ctx, req.(*iam_pb.RemoveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HanzoS3IamCache_ServiceDesc is the grpc.ServiceDesc for HanzoS3IamCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HanzoS3IamCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messaging_pb.HanzoS3IamCache",
	HandlerType: (*HanzoS3IamCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutIdentity",
			Handler:    _HanzoS3IamCache_PutIdentity_Handler,
		},
		{
			MethodName: "RemoveIdentity",
			Handler:    _HanzoS3IamCache_RemoveIdentity_Handler,
		},
		{
			MethodName: "PutPolicy",
			Handler:    _HanzoS3IamCache_PutPolicy_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _HanzoS3IamCache_GetPolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _HanzoS3IamCache_ListPolicies_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _HanzoS3IamCache_DeletePolicy_Handler,
		},
		{
			MethodName: "PutGroup",
			Handler:    _HanzoS3IamCache_PutGroup_Handler,
		},
		{
			MethodName: "RemoveGroup",
			Handler:    _HanzoS3IamCache_RemoveGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s3.proto",
}
