// Command protoc-gen-zap is the one-time migration generator that replaces
// protoc-gen-go + protoc-gen-go-grpc for Hanzo S3. From the existing .proto
// schemas it emits protobuf-free Go: plain message structs + GetX getters +
// MarshalZap/UnmarshalZap over the hand-rolled TLV codec (s3/zaprpc), plus
// per-service ZAP client/server stubs. The generated *_zap.go files replace the
// *.pb.go files; once every package is generated the .proto files and the
// protobuf/grpc dependencies are deleted — protoc is a migration tool, not a
// runtime dependency.
//
// Usage (driven from s3/pb/Makefile):
//
//	protoc --zap_out=paths=source_relative:. <file>.proto
package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(1) // FEATURE_PROTO3_OPTIONAL
		for _, f := range gen.Files {
			if f.Generate {
				generateFile(gen, f)
			}
		}
		return nil
	})
}

const codecPkg = "github.com/hanzoai/s3/s3/zaprpc"

func generateFile(gen *protogen.Plugin, f *protogen.File) {
	if len(f.Messages) == 0 && len(f.Services) == 0 {
		return
	}
	g := gen.NewGeneratedFile(f.GeneratedFilenamePrefix+"_zap.go", f.GoImportPath)
	g.P("// Code generated by protoc-gen-zap. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P("//")
	g.P("// Protobuf-free: plain structs + hand-rolled TLV codec over ZAP. The")
	g.P("// .proto is the one-time schema source; this output replaces the .pb.go.")
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()
	codec := g.QualifiedGoIdent(protogen.GoImportPath(codecPkg).Ident(""))
	codec = strings.TrimSuffix(codec, ".")
	for _, e := range f.Enums {
		genEnum(g, e)
	}
	for _, m := range f.Messages {
		genMessage(g, m, codec)
	}
	for _, svc := range f.Services {
		genService(g, svc, codec)
	}
}

// ---- services -----------------------------------------------------------

const contextImport = "context"

func isStreaming(m *protogen.Method) bool {
	return m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer()
}

// genService emits, per gRPC service, the protobuf-free ZAP equivalent: a
// server interface, a Register<Svc>Server that binds each unary method to a
// procedure code on a zaprpc.Server, and a <Svc>Client whose methods marshal
// the request, Call over ZAP, and unmarshal the response. Streaming methods are
// declared but deferred to F4 (stream.go).
func genService(g *protogen.GeneratedFile, svc *protogen.Service, codec string) {
	ctx := g.QualifiedGoIdent(protogen.GoImportPath(contextImport).Ident("Context"))
	name := svc.GoName

	g.P("// ", name, "Server is the service interface (implement + Register).")
	g.P("type ", name, "Server interface {")
	for _, m := range svc.Methods {
		if isStreaming(m) {
			g.P("\t// ", m.GoName, ": streaming RPC — generated in F4 (stream.go).")
			continue
		}
		g.P("\t", m.GoName, "(", ctx, ", *", g.QualifiedGoIdent(m.Input.GoIdent), ") (*", g.QualifiedGoIdent(m.Output.GoIdent), ", error)")
	}
	g.P("}")
	g.P()

	g.P("const (")
	code := 1
	for _, m := range svc.Methods {
		if isStreaming(m) {
			continue
		}
		g.P("\tcode", name, m.GoName, " uint8 = ", code)
		code++
	}
	g.P(")")
	g.P()

	g.P("func Register", name, "Server(s *", codec, ".Server, impl ", name, "Server) {")
	for _, m := range svc.Methods {
		if isStreaming(m) {
			continue
		}
		g.P("\ts.Handle(code", name, m.GoName, ", func(ctx ", ctx, ", req []byte) ([]byte, error) {")
		g.P("\t\tvar in ", g.QualifiedGoIdent(m.Input.GoIdent))
		g.P("\t\tif err := in.UnmarshalZap(req); err != nil { return nil, err }")
		g.P("\t\tout, err := impl.", m.GoName, "(ctx, &in)")
		g.P("\t\tif err != nil { return nil, err }")
		g.P("\t\treturn out.MarshalZap(), nil")
		g.P("\t})")
	}
	g.P("}")
	g.P()

	g.P("type ", name, "Client struct {")
	g.P("\tC    *", codec, ".Client")
	g.P("\tAddr string")
	g.P("}")
	g.P("func New", name, "Client(c *", codec, ".Client, addr string) *", name, "Client {")
	g.P("\treturn &", name, "Client{C: c, Addr: addr}")
	g.P("}")
	for _, m := range svc.Methods {
		if isStreaming(m) {
			continue
		}
		in := g.QualifiedGoIdent(m.Input.GoIdent)
		out := g.QualifiedGoIdent(m.Output.GoIdent)
		g.P("func (x *", name, "Client) ", m.GoName, "(ctx ", ctx, ", req *", in, ") (*", out, ", error) {")
		g.P("\tresp, err := x.C.Call(ctx, x.Addr, code", name, m.GoName, ", req.MarshalZap())")
		g.P("\tif err != nil { return nil, err }")
		g.P("\tvar res ", out)
		g.P("\tif err := res.UnmarshalZap(resp); err != nil { return nil, err }")
		g.P("\treturn &res, nil")
		g.P("}")
	}
	g.P()
}

// ---- enums --------------------------------------------------------------

func genEnum(g *protogen.GeneratedFile, e *protogen.Enum) {
	name := e.GoIdent.GoName
	g.P("type ", name, " int32")
	g.P("const (")
	for _, v := range e.Values {
		g.P("\t", v.GoIdent.GoName, " ", name, " = ", v.Desc.Number())
	}
	g.P(")")
	g.P()
}

// ---- messages -----------------------------------------------------------

func genMessage(g *protogen.GeneratedFile, m *protogen.Message, codec string) {
	if m.Desc.IsMapEntry() {
		return // map entries are synthesized inline at the field site
	}
	name := m.GoIdent.GoName

	// struct
	g.P("type ", name, " struct {")
	for _, field := range m.Fields {
		g.P("\t", field.GoName, " ", goType(g, field), " // ", field.Desc.Number())
	}
	g.P("}")
	g.P()

	// getters (consumer code uses GetX())
	for _, field := range m.Fields {
		gt := goType(g, field)
		g.P("func (m *", name, ") Get", field.GoName, "() ", gt, " {")
		g.P("\tif m == nil { return ", zeroValue(g, field), " }")
		g.P("\treturn m.", field.GoName)
		g.P("}")
	}
	g.P()

	genMarshal(g, m, codec)
	genUnmarshal(g, m, codec)

	for _, nested := range m.Messages {
		genMessage(g, nested, codec)
	}
	for _, e := range m.Enums {
		genEnum(g, e)
	}
}

func genMarshal(g *protogen.GeneratedFile, m *protogen.Message, codec string) {
	name := m.GoIdent.GoName
	g.P("func (m *", name, ") MarshalZap() []byte {")
	g.P("\tw := ", codec, ".NewWriter()")
	for _, field := range m.Fields {
		marshalField(g, field, codec)
	}
	g.P("\treturn w.Result()")
	g.P("}")
	g.P()
}

func marshalField(g *protogen.GeneratedFile, field *protogen.Field, codec string) {
	n := field.Desc.Number()
	ref := "m." + field.GoName
	switch {
	case field.Desc.IsMap():
		key := field.Message.Fields[0]
		val := field.Message.Fields[1]
		g.P("\tfor k, v := range ", ref, " {")
		g.P("\t\tew := ", codec, ".NewWriter()")
		marshalScalarTo(g, "ew", key, 1, "k")
		marshalValueTo(g, "ew", val, 2, "v")
		g.P("\t\tw.Message(", n, ", ew.Result())")
		g.P("\t}")
	case field.Desc.IsList():
		g.P("\tfor _, e := range ", ref, " {")
		marshalRepeatedElem(g, field, n, "e")
		g.P("\t}")
	case field.Message != nil:
		g.P("\tif ", ref, " != nil { w.Message(", n, ", ", ref, ".MarshalZap()) }")
	default:
		marshalScalarTo(g, "w", field, int(n), ref)
	}
}

// marshalScalarTo emits a single scalar write (zero-omitting form).
func marshalScalarTo(g *protogen.GeneratedFile, w string, field *protogen.Field, num int, expr string) {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		g.P("\t\t", w, ".Bool(", num, ", ", expr, ")")
	case protoreflect.StringKind:
		g.P("\t\t", w, ".String(", num, ", ", expr, ")")
	case protoreflect.BytesKind:
		g.P("\t\t", w, ".Bytes(", num, ", ", expr, ")")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("\t\t", w, ".Int32(", num, ", int32(", expr, "))")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("\t\t", w, ".Int64(", num, ", int64(", expr, "))")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("\t\t", w, ".Uint32(", num, ", uint32(", expr, "))")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("\t\t", w, ".Uint64(", num, ", uint64(", expr, "))")
	case protoreflect.EnumKind:
		g.P("\t\t", w, ".Int32(", num, ", int32(", expr, "))")
	case protoreflect.FloatKind:
		g.P("\t\t", w, ".Float(", num, ", ", expr, ")")
	case protoreflect.DoubleKind:
		g.P("\t\t", w, ".Double(", num, ", ", expr, ")")
	default:
		g.P("\t\t// TODO unsupported scalar kind ", field.Desc.Kind().String())
	}
}

func marshalValueTo(g *protogen.GeneratedFile, w string, field *protogen.Field, num int, expr string) {
	if field.Message != nil {
		g.P("\t\t", w, ".Message(", num, ", ", expr, ".MarshalZap())")
		return
	}
	marshalScalarTo(g, w, field, num, expr)
}

func marshalRepeatedElem(g *protogen.GeneratedFile, field *protogen.Field, num protoreflect.FieldNumber, expr string) {
	if field.Message != nil {
		g.P("\t\tw.Message(", num, ", ", expr, ".MarshalZap())")
		return
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P("\t\tw.RawString(", num, ", ", expr, ")")
	case protoreflect.BytesKind:
		g.P("\t\tw.Bytes(", num, ", ", expr, ")")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("\t\tw.RawUint64(", num, ", uint64(", expr, "))")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("\t\tw.RawUint64(", num, ", uint64(", expr, "))")
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.EnumKind:
		g.P("\t\tw.RawUint64(", num, ", uint64(", expr, "))")
	default:
		g.P("\t\t// TODO repeated kind ", field.Desc.Kind().String())
	}
}

func genUnmarshal(g *protogen.GeneratedFile, m *protogen.Message, codec string) {
	name := m.GoIdent.GoName
	g.P("func (m *", name, ") UnmarshalZap(b []byte) error {")
	g.P("\tr := ", codec, ".NewReader(b)")
	g.P("\tfor r.Next() {")
	g.P("\t\tswitch r.Field() {")
	for _, field := range m.Fields {
		g.P("\t\tcase ", field.Desc.Number(), ":")
		unmarshalField(g, field, codec)
	}
	g.P("\t\tdefault:")
	g.P("\t\t\tr.Skip()")
	g.P("\t\t}")
	g.P("\t}")
	g.P("\treturn r.Err()")
	g.P("}")
	g.P()
}

func unmarshalField(g *protogen.GeneratedFile, field *protogen.Field, codec string) {
	ref := "m." + field.GoName
	switch {
	case field.Desc.IsMap():
		key := field.Message.Fields[0]
		val := field.Message.Fields[1]
		g.P("\t\t\tif ", ref, " == nil { ", ref, " = ", goType(g, field), "{} }")
		g.P("\t\t\ter := ", codec, ".NewReader(r.Message())")
		g.P("\t\t\tvar mk ", goType(g, key))
		g.P("\t\t\tvar mv ", goType(g, val))
		if val.Message != nil {
			g.P("\t\t\tmv = &", val.Message.GoIdent.GoName, "{}")
		}
		g.P("\t\t\tfor er.Next() {")
		g.P("\t\t\t\tswitch er.Field() {")
		g.P("\t\t\t\tcase 1:")
		readScalarInto(g, "er", key, "mk")
		g.P("\t\t\t\tcase 2:")
		if val.Message != nil {
			g.P("\t\t\t\t\t_ = mv.UnmarshalZap(er.Message())")
		} else {
			readScalarInto(g, "er", val, "mv")
		}
		g.P("\t\t\t\tdefault: er.Skip()")
		g.P("\t\t\t\t}")
		g.P("\t\t\t}")
		g.P("\t\t\t", ref, "[mk] = mv")
	case field.Desc.IsList():
		if field.Message != nil {
			g.P("\t\t\t{ e := &", field.Message.GoIdent.GoName, "{}; _ = e.UnmarshalZap(r.Message()); ", ref, " = append(", ref, ", e) }")
		} else {
			elemType := goScalarType(field)
			g.P("\t\t\t", ref, " = append(", ref, ", ", readScalarExpr(field, elemType), ")")
		}
	case field.Message != nil:
		g.P("\t\t\t{ e := &", field.Message.GoIdent.GoName, "{}; _ = e.UnmarshalZap(r.Message()); ", ref, " = e }")
	default:
		readScalarInto(g, "r", field, ref)
	}
}

func readScalarInto(g *protogen.GeneratedFile, r string, field *protogen.Field, lhs string) {
	g.P("\t\t\t\t\t", lhs, " = ", readScalarExprR(r, field, goScalarType(field)))
}

func readScalarExpr(field *protogen.Field, cast string) string {
	return readScalarExprR("r", field, cast)
}

func readScalarExprR(r string, field *protogen.Field, cast string) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return r + ".Bool()"
	case protoreflect.StringKind:
		return r + ".String()"
	case protoreflect.BytesKind:
		return r + ".Bytes()"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return cast + "(" + r + ".Int32())"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return cast + "(" + r + ".Int64())"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return cast + "(" + r + ".Uint32())"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return cast + "(" + r + ".Uint64())"
	case protoreflect.EnumKind:
		return cast + "(" + r + ".Int32())"
	case protoreflect.FloatKind:
		return r + ".Float()"
	case protoreflect.DoubleKind:
		return r + ".Double()"
	}
	return cast + "(" + r + ".Uint64())"
}

// ---- type mapping -------------------------------------------------------

func goType(g *protogen.GeneratedFile, field *protogen.Field) string {
	if field.Desc.IsMap() {
		k := goScalarType(field.Message.Fields[0])
		v := field.Message.Fields[1]
		vt := goScalarType(v)
		if v.Message != nil {
			vt = "*" + v.Message.GoIdent.GoName
		}
		return "map[" + k + "]" + vt
	}
	if field.Desc.IsList() {
		if field.Message != nil {
			return "[]*" + field.Message.GoIdent.GoName
		}
		return "[]" + goScalarType(field)
	}
	if field.Message != nil {
		return "*" + field.Message.GoIdent.GoName
	}
	if field.Enum != nil {
		return field.Enum.GoIdent.GoName
	}
	return goScalarType(field)
}

func goScalarType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.EnumKind:
		if field.Enum != nil {
			return field.Enum.GoIdent.GoName
		}
		return "int32"
	}
	return "[]byte"
}

func zeroValue(g *protogen.GeneratedFile, field *protogen.Field) string {
	if field.Desc.IsMap() || field.Desc.IsList() || field.Message != nil || field.Desc.Kind() == protoreflect.BytesKind {
		return "nil"
	}
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.StringKind:
		return `""`
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return "0"
	}
	if field.Enum != nil {
		return field.Enum.GoIdent.GoName + "(0)"
	}
	return "0"
}
