// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: plugin.proto
//
// gRPC ripped: this file holds only the grpc-free PluginControlService
// contracts. The client interface returns the shared rpc.* stream seams; the
// server interface is the plain method set. The service rides the ZAP transport
// (see s3/wire/plugin), whose Dispatch serves it. No grpc client/server
// scaffolding remains.

package plugin_pb

import (
	context "context"

	"github.com/hanzoai/s3/s3/pb/rpc"
)

const (
	PluginControlService_WorkerStream_FullMethodName = "/plugin.PluginControlService/WorkerStream"
)

// PluginControlServiceClient is the client API for PluginControlService service.
//
// PluginControlService is the admin-facing stream API for external workers.
// Workers initiate and keep this stream alive; all control plane traffic flows through it.
type PluginControlServiceClient interface {
	WorkerStream(ctx context.Context) (rpc.BidiStream[WorkerToAdminMessage, AdminToWorkerMessage], error)
}

// PluginControlService_WorkerStreamServer is the server side of the WorkerStream bidi-stream.
type PluginControlService_WorkerStreamServer interface {
	Send(*AdminToWorkerMessage) error
	Recv() (*WorkerToAdminMessage, error)
}

// PluginControlServiceServer is the server API for PluginControlService service:
// the plain method set, transport-free.
//
// PluginControlService is the admin-facing stream API for external workers.
// Workers initiate and keep this stream alive; all control plane traffic flows through it.
type PluginControlServiceServer interface {
	WorkerStream(PluginControlService_WorkerStreamServer) error
}
