// Package zaprpc is the ZAP-native data + transport layer for Hanzo S3. It
// replaces protobuf, gRPC, and the _pb packages outright — there is no codec,
// no Marshal/Unmarshal, and no interop with protobuf.
//
// The model is zero-copy, the way ZAP is meant to be used:
//
//   - A message type is a ZAP schema (a zapv2 marker type with Kind/Size and
//     byte-offset field accessors), generated by github.com/luxfi/zap/v2/codegen
//     from a schema definition — NOT transpiled from a .proto.
//   - Producers BUILD directly into the wire buffer: New<Msg>(fields...) returns
//     (zapv2.View, []byte) in one allocation. There is no intermediate struct to
//     populate and then serialize.
//   - Consumers READ in place: Wrap<Msg>(buf) returns a zapv2.View; field
//     accessors read straight off the bytes. There is no deserialization step —
//     the bytes ARE the message.
//   - RPC carries these buffers natively over the ZAP transport (direct-addressed
//     zap.Node, no mDNS). The request/response ARE schema messages; the wire
//     message's Kind discriminates type. Nothing is re-encoded.
//
// What this deletes: every *_pb package, every .proto, protoc/protoc-gen-go/
// protoc-gen-go-grpc, google.golang.org/grpc, google.golang.org/protobuf, and
// any Marshal/Unmarshal round-trip. Messages are immutable ZAP values — build
// once, read many — which is also why mutation-heavy engine code migrates to a
// value-oriented form rather than a place-oriented (mutable-struct) one.
package zaprpc
