// Copyright (C) 2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.
//
// Code generated by github.com/luxfi/zap/v1/codegen — DO NOT EDIT.
// Source schema: GetObjectResponse (kind=0x11, size=32).

package wire

import (
	"github.com/luxfi/zap"
	zapv1 "github.com/luxfi/zap/v1"
)

// KindGetObjectResponse is the wire discriminator for GetObjectResponse.
const KindGetObjectResponse zapv1.KindByte = 0x11

// SizeGetObjectResponse is the fixed object payload size in bytes.
const SizeGetObjectResponse = 32

// GetObjectResponse is the v1 schema marker for GetObjectResponse. Methods are constant-
// returning so concrete-typed [zapv1.Wrap[GetObjectResponse]] calls fold to
// literals at the call site.
type GetObjectResponse struct{}

func (GetObjectResponse) Kind() zapv1.KindByte { return KindGetObjectResponse }
func (GetObjectResponse) Size() int            { return SizeGetObjectResponse }
func (GetObjectResponse) Name() string         { return "GetObjectResponse" }

// OffsetGetObjectResponse_Data is the byte offset of the Data field.
const OffsetGetObjectResponse_Data = 8

// OffsetGetObjectResponse_ContentType is the byte offset of the ContentType field.
const OffsetGetObjectResponse_ContentType = 16

// OffsetGetObjectResponse_Etag is the byte offset of the Etag field.
const OffsetGetObjectResponse_Etag = 24

// GetObjectResponseFields is empty: GetObjectResponse has no scalar fields.
var GetObjectResponseFields = struct{}{}

// NewGetObjectResponse builds a fresh GetObjectResponse in a ZAP buffer.
//
// Hand-rolled fast path: inlines v1 primitives ([zap.NewBuilder],
// [*Builder.StartObject], [*ObjectBuilder.Set*], [*Builder.Finish])
// so the entire build expands at the call site. Scalars and fixed byte
// arrays live in the fixed payload; variable-length string/bytes go in
// the object tail (the fixed payload holds their 8-byte pointers).
func NewGetObjectResponse(data []byte, contentType string, etag string) (zapv1.View[GetObjectResponse], []byte) {
	b := zap.NewBuilder(zap.HeaderSize + SizeGetObjectResponse + len(data) + len(contentType) + len(etag))
	ob := b.StartObject(SizeGetObjectResponse)
	ob.SetUint8(0, uint8(KindGetObjectResponse))
	ob.SetBytes(OffsetGetObjectResponse_Data, data)
	ob.SetText(OffsetGetObjectResponse_ContentType, contentType)
	ob.SetText(OffsetGetObjectResponse_Etag, etag)
	rootOff := ob.FinishAsRoot()
	buf := b.Finish()
	end := rootOff + SizeGetObjectResponse
	return zapv1.AsView[GetObjectResponse](zapv1.RawFromSlices(buf, rootOff, end)), buf
}

// WrapGetObjectResponse parses a ZAP buffer into a typed
// [zapv1.View[GetObjectResponse]]. Validates the wire frame and the kind
// discriminator at offset 0; returns [*zapv1.SchemaError] on kind
// mismatch.
//
// Hand-rolled fast path: inlines [zap.Parse] (which is itself
// inlineable). Zero heap allocs on the happy path; matches v1
// hand-rolled performance.
func WrapGetObjectResponse(b []byte) (zapv1.View[GetObjectResponse], error) {
	msg, err := zap.Parse(b)
	if err != nil {
		return zapv1.View[GetObjectResponse]{}, err
	}
	root := msg.Root()
	if got := root.Uint8(0); got != uint8(KindGetObjectResponse) {
		return zapv1.View[GetObjectResponse]{}, zapv1.NewSchemaError(
			KindGetObjectResponse, zapv1.KindByte(got), "GetObjectResponse")
	}
	data := msg.Bytes()
	rootOff := root.Offset()
	end := rootOff + SizeGetObjectResponse
	if end > len(data) {
		end = len(data) // Read returns zero on OOB; v1 graceful degradation
	}
	return zapv1.AsView[GetObjectResponse](zapv1.RawFromSlices(data, rootOff, end)), nil
}

// GetObjectResponseData reads the variable-length Data bytes field of GetObjectResponse.
//
// Zero-copy: v1's Object.Bytes returns a sub-slice of the underlying
// buffer. Valid only while the View's buffer is alive; copy to retain.
func GetObjectResponseData(v zapv1.View[GetObjectResponse]) []byte {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Bytes(OffsetGetObjectResponse_Data)
}

// GetObjectResponseContentType reads the variable-length ContentType string field of GetObjectResponse.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func GetObjectResponseContentType(v zapv1.View[GetObjectResponse]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetGetObjectResponse_ContentType)
}

// GetObjectResponseEtag reads the variable-length Etag string field of GetObjectResponse.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func GetObjectResponseEtag(v zapv1.View[GetObjectResponse]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetGetObjectResponse_Etag)
}

