// Copyright (C) 2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.
//
// Code generated by github.com/luxfi/zap/v1/codegen — DO NOT EDIT.
// Source schema: GetObjectRequest (kind=0x10, size=24).

package wire

import (
	"github.com/luxfi/zap"
	zapv1 "github.com/luxfi/zap/v1"
)

// KindGetObjectRequest is the wire discriminator for GetObjectRequest.
const KindGetObjectRequest zapv1.KindByte = 0x10

// SizeGetObjectRequest is the fixed object payload size in bytes.
const SizeGetObjectRequest = 24

// GetObjectRequest is the v1 schema marker for GetObjectRequest. Methods are constant-
// returning so concrete-typed [zapv1.Wrap[GetObjectRequest]] calls fold to
// literals at the call site.
type GetObjectRequest struct{}

func (GetObjectRequest) Kind() zapv1.KindByte { return KindGetObjectRequest }
func (GetObjectRequest) Size() int            { return SizeGetObjectRequest }
func (GetObjectRequest) Name() string         { return "GetObjectRequest" }

// OffsetGetObjectRequest_Bucket is the byte offset of the Bucket field.
const OffsetGetObjectRequest_Bucket = 8

// OffsetGetObjectRequest_Key is the byte offset of the Key field.
const OffsetGetObjectRequest_Key = 16

// GetObjectRequestFields is empty: GetObjectRequest has no scalar fields.
var GetObjectRequestFields = struct{}{}

// NewGetObjectRequest builds a fresh GetObjectRequest in a ZAP buffer.
//
// Hand-rolled fast path: inlines v1 primitives ([zap.NewBuilder],
// [*Builder.StartObject], [*ObjectBuilder.Set*], [*Builder.Finish])
// so the entire build expands at the call site. Scalars and fixed byte
// arrays live in the fixed payload; variable-length string/bytes go in
// the object tail (the fixed payload holds their 8-byte pointers).
func NewGetObjectRequest(bucket string, key string) (zapv1.View[GetObjectRequest], []byte) {
	b := zap.NewBuilder(zap.HeaderSize + SizeGetObjectRequest + len(bucket) + len(key))
	ob := b.StartObject(SizeGetObjectRequest)
	ob.SetUint8(0, uint8(KindGetObjectRequest))
	ob.SetText(OffsetGetObjectRequest_Bucket, bucket)
	ob.SetText(OffsetGetObjectRequest_Key, key)
	rootOff := ob.FinishAsRoot()
	buf := b.Finish()
	end := rootOff + SizeGetObjectRequest
	return zapv1.AsView[GetObjectRequest](zapv1.RawFromSlices(buf, rootOff, end)), buf
}

// WrapGetObjectRequest parses a ZAP buffer into a typed
// [zapv1.View[GetObjectRequest]]. Validates the wire frame and the kind
// discriminator at offset 0; returns [*zapv1.SchemaError] on kind
// mismatch.
//
// Hand-rolled fast path: inlines [zap.Parse] (which is itself
// inlineable). Zero heap allocs on the happy path; matches v1
// hand-rolled performance.
func WrapGetObjectRequest(b []byte) (zapv1.View[GetObjectRequest], error) {
	msg, err := zap.Parse(b)
	if err != nil {
		return zapv1.View[GetObjectRequest]{}, err
	}
	root := msg.Root()
	if got := root.Uint8(0); got != uint8(KindGetObjectRequest) {
		return zapv1.View[GetObjectRequest]{}, zapv1.NewSchemaError(
			KindGetObjectRequest, zapv1.KindByte(got), "GetObjectRequest")
	}
	data := msg.Bytes()
	rootOff := root.Offset()
	end := rootOff + SizeGetObjectRequest
	if end > len(data) {
		end = len(data) // Read returns zero on OOB; v1 graceful degradation
	}
	return zapv1.AsView[GetObjectRequest](zapv1.RawFromSlices(data, rootOff, end)), nil
}

// GetObjectRequestBucket reads the variable-length Bucket string field of GetObjectRequest.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func GetObjectRequestBucket(v zapv1.View[GetObjectRequest]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetGetObjectRequest_Bucket)
}

// GetObjectRequestKey reads the variable-length Key string field of GetObjectRequest.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func GetObjectRequestKey(v zapv1.View[GetObjectRequest]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetGetObjectRequest_Key)
}

