// Copyright (C) 2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.
//
// Code generated by github.com/luxfi/zap/v1/codegen — DO NOT EDIT.
// Source schema: PutObjectResponse (kind=0x13, size=16).

package wire

import (
	"github.com/luxfi/zap"
	zapv1 "github.com/luxfi/zap/v1"
)

// KindPutObjectResponse is the wire discriminator for PutObjectResponse.
const KindPutObjectResponse zapv1.KindByte = 0x13

// SizePutObjectResponse is the fixed object payload size in bytes.
const SizePutObjectResponse = 16

// PutObjectResponse is the v1 schema marker for PutObjectResponse. Methods are constant-
// returning so concrete-typed [zapv1.Wrap[PutObjectResponse]] calls fold to
// literals at the call site.
type PutObjectResponse struct{}

func (PutObjectResponse) Kind() zapv1.KindByte { return KindPutObjectResponse }
func (PutObjectResponse) Size() int            { return SizePutObjectResponse }
func (PutObjectResponse) Name() string         { return "PutObjectResponse" }

// OffsetPutObjectResponse_Etag is the byte offset of the Etag field.
const OffsetPutObjectResponse_Etag = 8

// PutObjectResponseFields is empty: PutObjectResponse has no scalar fields.
var PutObjectResponseFields = struct{}{}

// NewPutObjectResponse builds a fresh PutObjectResponse in a ZAP buffer.
//
// Hand-rolled fast path: inlines v1 primitives ([zap.NewBuilder],
// [*Builder.StartObject], [*ObjectBuilder.Set*], [*Builder.Finish])
// so the entire build expands at the call site. Scalars and fixed byte
// arrays live in the fixed payload; variable-length string/bytes go in
// the object tail (the fixed payload holds their 8-byte pointers).
func NewPutObjectResponse(etag string) (zapv1.View[PutObjectResponse], []byte) {
	b := zap.NewBuilder(zap.HeaderSize + SizePutObjectResponse + len(etag))
	ob := b.StartObject(SizePutObjectResponse)
	ob.SetUint8(0, uint8(KindPutObjectResponse))
	ob.SetText(OffsetPutObjectResponse_Etag, etag)
	rootOff := ob.FinishAsRoot()
	buf := b.Finish()
	end := rootOff + SizePutObjectResponse
	return zapv1.AsView[PutObjectResponse](zapv1.RawFromSlices(buf, rootOff, end)), buf
}

// WrapPutObjectResponse parses a ZAP buffer into a typed
// [zapv1.View[PutObjectResponse]]. Validates the wire frame and the kind
// discriminator at offset 0; returns [*zapv1.SchemaError] on kind
// mismatch.
//
// Hand-rolled fast path: inlines [zap.Parse] (which is itself
// inlineable). Zero heap allocs on the happy path; matches v1
// hand-rolled performance.
func WrapPutObjectResponse(b []byte) (zapv1.View[PutObjectResponse], error) {
	msg, err := zap.Parse(b)
	if err != nil {
		return zapv1.View[PutObjectResponse]{}, err
	}
	root := msg.Root()
	if got := root.Uint8(0); got != uint8(KindPutObjectResponse) {
		return zapv1.View[PutObjectResponse]{}, zapv1.NewSchemaError(
			KindPutObjectResponse, zapv1.KindByte(got), "PutObjectResponse")
	}
	data := msg.Bytes()
	rootOff := root.Offset()
	end := rootOff + SizePutObjectResponse
	if end > len(data) {
		end = len(data) // Read returns zero on OOB; v1 graceful degradation
	}
	return zapv1.AsView[PutObjectResponse](zapv1.RawFromSlices(data, rootOff, end)), nil
}

// PutObjectResponseEtag reads the variable-length Etag string field of PutObjectResponse.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func PutObjectResponseEtag(v zapv1.View[PutObjectResponse]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetPutObjectResponse_Etag)
}

