// Copyright (C) 2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.
//
// Code generated by github.com/luxfi/zap/v1/codegen — DO NOT EDIT.
// Source schema: PutObjectRequest (kind=0x12, size=40).

package wire

import (
	"github.com/luxfi/zap"
	zapv1 "github.com/luxfi/zap/v1"
)

// KindPutObjectRequest is the wire discriminator for PutObjectRequest.
const KindPutObjectRequest zapv1.KindByte = 0x12

// SizePutObjectRequest is the fixed object payload size in bytes.
const SizePutObjectRequest = 40

// PutObjectRequest is the v1 schema marker for PutObjectRequest. Methods are constant-
// returning so concrete-typed [zapv1.Wrap[PutObjectRequest]] calls fold to
// literals at the call site.
type PutObjectRequest struct{}

func (PutObjectRequest) Kind() zapv1.KindByte { return KindPutObjectRequest }
func (PutObjectRequest) Size() int            { return SizePutObjectRequest }
func (PutObjectRequest) Name() string         { return "PutObjectRequest" }

// OffsetPutObjectRequest_Bucket is the byte offset of the Bucket field.
const OffsetPutObjectRequest_Bucket = 8

// OffsetPutObjectRequest_Key is the byte offset of the Key field.
const OffsetPutObjectRequest_Key = 16

// OffsetPutObjectRequest_Data is the byte offset of the Data field.
const OffsetPutObjectRequest_Data = 24

// OffsetPutObjectRequest_ContentType is the byte offset of the ContentType field.
const OffsetPutObjectRequest_ContentType = 32

// PutObjectRequestFields is empty: PutObjectRequest has no scalar fields.
var PutObjectRequestFields = struct{}{}

// NewPutObjectRequest builds a fresh PutObjectRequest in a ZAP buffer.
//
// Hand-rolled fast path: inlines v1 primitives ([zap.NewBuilder],
// [*Builder.StartObject], [*ObjectBuilder.Set*], [*Builder.Finish])
// so the entire build expands at the call site. Scalars and fixed byte
// arrays live in the fixed payload; variable-length string/bytes go in
// the object tail (the fixed payload holds their 8-byte pointers).
func NewPutObjectRequest(bucket string, key string, data []byte, contentType string) (zapv1.View[PutObjectRequest], []byte) {
	b := zap.NewBuilder(zap.HeaderSize + SizePutObjectRequest + len(bucket) + len(key) + len(data) + len(contentType))
	ob := b.StartObject(SizePutObjectRequest)
	ob.SetUint8(0, uint8(KindPutObjectRequest))
	ob.SetText(OffsetPutObjectRequest_Bucket, bucket)
	ob.SetText(OffsetPutObjectRequest_Key, key)
	ob.SetBytes(OffsetPutObjectRequest_Data, data)
	ob.SetText(OffsetPutObjectRequest_ContentType, contentType)
	rootOff := ob.FinishAsRoot()
	buf := b.Finish()
	end := rootOff + SizePutObjectRequest
	return zapv1.AsView[PutObjectRequest](zapv1.RawFromSlices(buf, rootOff, end)), buf
}

// WrapPutObjectRequest parses a ZAP buffer into a typed
// [zapv1.View[PutObjectRequest]]. Validates the wire frame and the kind
// discriminator at offset 0; returns [*zapv1.SchemaError] on kind
// mismatch.
//
// Hand-rolled fast path: inlines [zap.Parse] (which is itself
// inlineable). Zero heap allocs on the happy path; matches v1
// hand-rolled performance.
func WrapPutObjectRequest(b []byte) (zapv1.View[PutObjectRequest], error) {
	msg, err := zap.Parse(b)
	if err != nil {
		return zapv1.View[PutObjectRequest]{}, err
	}
	root := msg.Root()
	if got := root.Uint8(0); got != uint8(KindPutObjectRequest) {
		return zapv1.View[PutObjectRequest]{}, zapv1.NewSchemaError(
			KindPutObjectRequest, zapv1.KindByte(got), "PutObjectRequest")
	}
	data := msg.Bytes()
	rootOff := root.Offset()
	end := rootOff + SizePutObjectRequest
	if end > len(data) {
		end = len(data) // Read returns zero on OOB; v1 graceful degradation
	}
	return zapv1.AsView[PutObjectRequest](zapv1.RawFromSlices(data, rootOff, end)), nil
}

// PutObjectRequestBucket reads the variable-length Bucket string field of PutObjectRequest.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func PutObjectRequestBucket(v zapv1.View[PutObjectRequest]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetPutObjectRequest_Bucket)
}

// PutObjectRequestKey reads the variable-length Key string field of PutObjectRequest.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func PutObjectRequestKey(v zapv1.View[PutObjectRequest]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetPutObjectRequest_Key)
}

// PutObjectRequestData reads the variable-length Data bytes field of PutObjectRequest.
//
// Zero-copy: v1's Object.Bytes returns a sub-slice of the underlying
// buffer. Valid only while the View's buffer is alive; copy to retain.
func PutObjectRequestData(v zapv1.View[PutObjectRequest]) []byte {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Bytes(OffsetPutObjectRequest_Data)
}

// PutObjectRequestContentType reads the variable-length ContentType string field of PutObjectRequest.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func PutObjectRequestContentType(v zapv1.View[PutObjectRequest]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv1.RootOff(v)))
	return obj.Text(OffsetPutObjectRequest_ContentType)
}

