// Copyright (C) 2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.
//
// Code generated by github.com/luxfi/zap/v2/codegen — DO NOT EDIT.
// Source schema: RemoteStorageLocation (kind=0x01, size=32).

package wiregen

import (
	"github.com/luxfi/zap"
	zapv2 "github.com/luxfi/zap/v2"
)

// KindRemoteStorageLocation is the wire discriminator for RemoteStorageLocation.
const KindRemoteStorageLocation zapv2.KindByte = 0x01

// SizeRemoteStorageLocation is the fixed object payload size in bytes.
const SizeRemoteStorageLocation = 32

// RSLSchema is the v2 schema marker for RemoteStorageLocation. Methods are constant-
// returning so concrete-typed [zapv2.Wrap[RSLSchema]] calls fold to
// literals at the call site.
type RSLSchema struct{}

func (RSLSchema) Kind() zapv2.KindByte { return KindRemoteStorageLocation }
func (RSLSchema) Size() int            { return SizeRemoteStorageLocation }
func (RSLSchema) Name() string         { return "RemoteStorageLocation" }

// OffsetRemoteStorageLocation_TTLSeconds is the byte offset of the TTLSeconds field.
const OffsetRemoteStorageLocation_TTLSeconds = 4

// OffsetRemoteStorageLocation_Name is the byte offset of the Name field.
const OffsetRemoteStorageLocation_Name = 8

// OffsetRemoteStorageLocation_Bucket is the byte offset of the Bucket field.
const OffsetRemoteStorageLocation_Bucket = 16

// OffsetRemoteStorageLocation_Path is the byte offset of the Path field.
const OffsetRemoteStorageLocation_Path = 24

// RSLSchemaFields is the namespace of every scalar field accessor for RemoteStorageLocation.
// Use with [zapv2.Read] / [zapv2.Write] for type-safe access.
// Byte-array fields are emitted as standalone functions, see below.
var RSLSchemaFields = struct {
	TTLSeconds zapv2.Field[RSLSchema, int32]
}{
	TTLSeconds: zapv2.At[RSLSchema, int32](4),
}

// NewRemoteStorageLocation builds a fresh RemoteStorageLocation in a ZAP buffer.
//
// Hand-rolled fast path: inlines v1 primitives ([zap.NewBuilder],
// [*Builder.StartObject], [*ObjectBuilder.Set*], [*Builder.Finish])
// so the entire build expands at the call site. Scalars and fixed byte
// arrays live in the fixed payload; variable-length string/bytes go in
// the object tail (the fixed payload holds their 8-byte pointers).
func NewRemoteStorageLocation(tTLSeconds int32, name string, bucket string, path string) (zapv2.View[RSLSchema], []byte) {
	b := zap.NewBuilder(zap.HeaderSize + SizeRemoteStorageLocation + len(name) + len(bucket) + len(path))
	ob := b.StartObject(SizeRemoteStorageLocation)
	ob.SetUint8(0, uint8(KindRemoteStorageLocation))
	ob.SetInt32(OffsetRemoteStorageLocation_TTLSeconds, tTLSeconds)
	ob.SetText(OffsetRemoteStorageLocation_Name, name)
	ob.SetText(OffsetRemoteStorageLocation_Bucket, bucket)
	ob.SetText(OffsetRemoteStorageLocation_Path, path)
	rootOff := ob.FinishAsRoot()
	buf := b.Finish()
	end := rootOff + SizeRemoteStorageLocation
	return zapv2.AsView[RSLSchema](zapv2.RawFromSlices(buf, rootOff, end)), buf
}

// WrapRemoteStorageLocation parses a ZAP buffer into a typed
// [zapv2.View[RemoteStorageLocation]]. Validates the wire frame and the kind
// discriminator at offset 0; returns [*zapv2.SchemaError] on kind
// mismatch.
//
// Hand-rolled fast path: inlines [zap.Parse] (which is itself
// inlineable). Zero heap allocs on the happy path; matches v1
// hand-rolled performance.
func WrapRemoteStorageLocation(b []byte) (zapv2.View[RSLSchema], error) {
	msg, err := zap.Parse(b)
	if err != nil {
		return zapv2.View[RSLSchema]{}, err
	}
	root := msg.Root()
	if got := root.Uint8(0); got != uint8(KindRemoteStorageLocation) {
		return zapv2.View[RSLSchema]{}, zapv2.NewSchemaError(
			KindRemoteStorageLocation, zapv2.KindByte(got), "RemoteStorageLocation")
	}
	data := msg.Bytes()
	rootOff := root.Offset()
	end := rootOff + SizeRemoteStorageLocation
	if end > len(data) {
		end = len(data) // Read returns zero on OOB; v1 graceful degradation
	}
	return zapv2.AsView[RSLSchema](zapv2.RawFromSlices(data, rootOff, end)), nil
}

// RemoteStorageLocationName reads the variable-length Name string field of RemoteStorageLocation.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func RemoteStorageLocationName(v zapv2.View[RSLSchema]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv2.RootOff(v)))
	return obj.Text(OffsetRemoteStorageLocation_Name)
}

// RemoteStorageLocationBucket reads the variable-length Bucket string field of RemoteStorageLocation.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func RemoteStorageLocationBucket(v zapv2.View[RSLSchema]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv2.RootOff(v)))
	return obj.Text(OffsetRemoteStorageLocation_Bucket)
}

// RemoteStorageLocationPath reads the variable-length Path string field of RemoteStorageLocation.
//
// Zero-copy: v1's Object.Text returns a string over a sub-slice of the
// underlying buffer. Valid only while the View's buffer is alive.
func RemoteStorageLocationPath(v zapv2.View[RSLSchema]) string {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv2.RootOff(v)))
	return obj.Text(OffsetRemoteStorageLocation_Path)
}

func init() {
	zapv2.Register[RSLSchema](zapv2.DefaultRegistry)
}
