// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: mount.proto

package mount_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HanzoMount_Configure_FullMethodName = "/messaging_pb.HanzoMount/Configure"
)

// HanzoMountClient is the client API for HanzoMount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HanzoMountClient interface {
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
}

type hanzoMountClient struct {
	cc grpc.ClientConnInterface
}

func NewHanzoMountClient(cc grpc.ClientConnInterface) HanzoMountClient {
	return &hanzoMountClient{cc}
}

func (c *hanzoMountClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, HanzoMount_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HanzoMountServer is the server API for HanzoMount service.
// All implementations must embed UnimplementedHanzoMountServer
// for forward compatibility.
type HanzoMountServer interface {
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	mustEmbedUnimplementedHanzoMountServer()
}

// UnimplementedHanzoMountServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHanzoMountServer struct{}

func (UnimplementedHanzoMountServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedHanzoMountServer) mustEmbedUnimplementedHanzoMountServer() {}
func (UnimplementedHanzoMountServer) testEmbeddedByValue()                    {}

// UnsafeHanzoMountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HanzoMountServer will
// result in compilation errors.
type UnsafeHanzoMountServer interface {
	mustEmbedUnimplementedHanzoMountServer()
}

func RegisterHanzoMountServer(s grpc.ServiceRegistrar, srv HanzoMountServer) {
	// If the following call panics, it indicates UnimplementedHanzoMountServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HanzoMount_ServiceDesc, srv)
}

func _HanzoMount_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoMountServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoMount_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoMountServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HanzoMount_ServiceDesc is the grpc.ServiceDesc for HanzoMount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HanzoMount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messaging_pb.HanzoMount",
	HandlerType: (*HanzoMountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _HanzoMount_Configure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mount.proto",
}
