// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: worker.proto
//
// gRPC ripped: this file holds only the grpc-free WorkerService contracts. The
// client interface returns the shared rpc.* stream seams; the server interface
// is the plain method set. The service rides the ZAP transport (see
// s3/wire/worker), whose Dispatch serves it. No grpc client/server scaffolding
// remains.

package worker_pb

import (
	context "context"

	"github.com/hanzoai/s3/s3/pb/rpc"
)

const (
	WorkerService_WorkerStream_FullMethodName = "/worker_pb.WorkerService/WorkerStream"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// WorkerService provides bidirectional communication between admin and worker
type WorkerServiceClient interface {
	// WorkerStream maintains a bidirectional stream for worker communication
	WorkerStream(ctx context.Context) (rpc.BidiStream[WorkerMessage, AdminMessage], error)
}

// WorkerService_WorkerStreamServer is the server side of the WorkerStream bidi-stream.
type WorkerService_WorkerStreamServer interface {
	Send(*AdminMessage) error
	Recv() (*WorkerMessage, error)
}

// WorkerServiceServer is the server API for WorkerService service: the plain
// method set, transport-free.
//
// WorkerService provides bidirectional communication between admin and worker
type WorkerServiceServer interface {
	// WorkerStream maintains a bidirectional stream for worker communication
	WorkerStream(WorkerService_WorkerStreamServer) error
}
