// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: mq_agent.proto

package mq_agent_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HanzoMessagingAgent_StartPublishSession_FullMethodName = "/messaging_pb.HanzoMessagingAgent/StartPublishSession"
	HanzoMessagingAgent_ClosePublishSession_FullMethodName = "/messaging_pb.HanzoMessagingAgent/ClosePublishSession"
	HanzoMessagingAgent_PublishRecord_FullMethodName       = "/messaging_pb.HanzoMessagingAgent/PublishRecord"
	HanzoMessagingAgent_SubscribeRecord_FullMethodName     = "/messaging_pb.HanzoMessagingAgent/SubscribeRecord"
)

// HanzoMessagingAgentClient is the client API for HanzoMessagingAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HanzoMessagingAgentClient interface {
	// Publishing
	StartPublishSession(ctx context.Context, in *StartPublishSessionRequest, opts ...grpc.CallOption) (*StartPublishSessionResponse, error)
	ClosePublishSession(ctx context.Context, in *ClosePublishSessionRequest, opts ...grpc.CallOption) (*ClosePublishSessionResponse, error)
	PublishRecord(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRecordRequest, PublishRecordResponse], error)
	// Subscribing
	SubscribeRecord(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRecordRequest, SubscribeRecordResponse], error)
}

type hanzoMessagingAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHanzoMessagingAgentClient(cc grpc.ClientConnInterface) HanzoMessagingAgentClient {
	return &hanzoMessagingAgentClient{cc}
}

func (c *hanzoMessagingAgentClient) StartPublishSession(ctx context.Context, in *StartPublishSessionRequest, opts ...grpc.CallOption) (*StartPublishSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPublishSessionResponse)
	err := c.cc.Invoke(ctx, HanzoMessagingAgent_StartPublishSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoMessagingAgentClient) ClosePublishSession(ctx context.Context, in *ClosePublishSessionRequest, opts ...grpc.CallOption) (*ClosePublishSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClosePublishSessionResponse)
	err := c.cc.Invoke(ctx, HanzoMessagingAgent_ClosePublishSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hanzoMessagingAgentClient) PublishRecord(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRecordRequest, PublishRecordResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HanzoMessagingAgent_ServiceDesc.Streams[0], HanzoMessagingAgent_PublishRecord_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishRecordRequest, PublishRecordResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HanzoMessagingAgent_PublishRecordClient = grpc.BidiStreamingClient[PublishRecordRequest, PublishRecordResponse]

func (c *hanzoMessagingAgentClient) SubscribeRecord(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRecordRequest, SubscribeRecordResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HanzoMessagingAgent_ServiceDesc.Streams[1], HanzoMessagingAgent_SubscribeRecord_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRecordRequest, SubscribeRecordResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HanzoMessagingAgent_SubscribeRecordClient = grpc.BidiStreamingClient[SubscribeRecordRequest, SubscribeRecordResponse]

// HanzoMessagingAgentServer is the server API for HanzoMessagingAgent service.
// All implementations must embed UnimplementedHanzoMessagingAgentServer
// for forward compatibility.
type HanzoMessagingAgentServer interface {
	// Publishing
	StartPublishSession(context.Context, *StartPublishSessionRequest) (*StartPublishSessionResponse, error)
	ClosePublishSession(context.Context, *ClosePublishSessionRequest) (*ClosePublishSessionResponse, error)
	PublishRecord(grpc.BidiStreamingServer[PublishRecordRequest, PublishRecordResponse]) error
	// Subscribing
	SubscribeRecord(grpc.BidiStreamingServer[SubscribeRecordRequest, SubscribeRecordResponse]) error
	mustEmbedUnimplementedHanzoMessagingAgentServer()
}

// UnimplementedHanzoMessagingAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHanzoMessagingAgentServer struct{}

func (UnimplementedHanzoMessagingAgentServer) StartPublishSession(context.Context, *StartPublishSessionRequest) (*StartPublishSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPublishSession not implemented")
}
func (UnimplementedHanzoMessagingAgentServer) ClosePublishSession(context.Context, *ClosePublishSessionRequest) (*ClosePublishSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePublishSession not implemented")
}
func (UnimplementedHanzoMessagingAgentServer) PublishRecord(grpc.BidiStreamingServer[PublishRecordRequest, PublishRecordResponse]) error {
	return status.Error(codes.Unimplemented, "method PublishRecord not implemented")
}
func (UnimplementedHanzoMessagingAgentServer) SubscribeRecord(grpc.BidiStreamingServer[SubscribeRecordRequest, SubscribeRecordResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRecord not implemented")
}
func (UnimplementedHanzoMessagingAgentServer) mustEmbedUnimplementedHanzoMessagingAgentServer() {}
func (UnimplementedHanzoMessagingAgentServer) testEmbeddedByValue()                             {}

// UnsafeHanzoMessagingAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HanzoMessagingAgentServer will
// result in compilation errors.
type UnsafeHanzoMessagingAgentServer interface {
	mustEmbedUnimplementedHanzoMessagingAgentServer()
}

func RegisterHanzoMessagingAgentServer(s grpc.ServiceRegistrar, srv HanzoMessagingAgentServer) {
	// If the following call panics, it indicates UnimplementedHanzoMessagingAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HanzoMessagingAgent_ServiceDesc, srv)
}

func _HanzoMessagingAgent_StartPublishSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPublishSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoMessagingAgentServer).StartPublishSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoMessagingAgent_StartPublishSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoMessagingAgentServer).StartPublishSession(ctx, req.(*StartPublishSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoMessagingAgent_ClosePublishSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePublishSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HanzoMessagingAgentServer).ClosePublishSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HanzoMessagingAgent_ClosePublishSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HanzoMessagingAgentServer).ClosePublishSession(ctx, req.(*ClosePublishSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HanzoMessagingAgent_PublishRecord_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HanzoMessagingAgentServer).PublishRecord(&grpc.GenericServerStream[PublishRecordRequest, PublishRecordResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HanzoMessagingAgent_PublishRecordServer = grpc.BidiStreamingServer[PublishRecordRequest, PublishRecordResponse]

func _HanzoMessagingAgent_SubscribeRecord_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HanzoMessagingAgentServer).SubscribeRecord(&grpc.GenericServerStream[SubscribeRecordRequest, SubscribeRecordResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HanzoMessagingAgent_SubscribeRecordServer = grpc.BidiStreamingServer[SubscribeRecordRequest, SubscribeRecordResponse]

// HanzoMessagingAgent_ServiceDesc is the grpc.ServiceDesc for HanzoMessagingAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HanzoMessagingAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messaging_pb.HanzoMessagingAgent",
	HandlerType: (*HanzoMessagingAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPublishSession",
			Handler:    _HanzoMessagingAgent_StartPublishSession_Handler,
		},
		{
			MethodName: "ClosePublishSession",
			Handler:    _HanzoMessagingAgent_ClosePublishSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishRecord",
			Handler:       _HanzoMessagingAgent_PublishRecord_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeRecord",
			Handler:       _HanzoMessagingAgent_SubscribeRecord_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mq_agent.proto",
}
