// Code generated by protoc-gen-zap. DO NOT EDIT.
// source: echo.proto
//
// Protobuf-free: plain structs + hand-rolled TLV codec over ZAP. The
// .proto is the one-time schema source; this output replaces the .pb.go.

package gentest

import (
	context "context"
	zaprpc "github.com/hanzoai/s3/s3/zaprpc"
)

type PingRequest struct {
	Msg  string   // 1
	Seq  int32    // 2
	Tags []string // 3
}

func (m *PingRequest) GetMsg() string {
	if m == nil {
		return ""
	}
	return m.Msg
}
func (m *PingRequest) GetSeq() int32 {
	if m == nil {
		return 0
	}
	return m.Seq
}
func (m *PingRequest) GetTags() []string {
	if m == nil {
		return nil
	}
	return m.Tags
}

func (m *PingRequest) MarshalZap() []byte {
	w := zaprpc.NewWriter()
	w.String(1, m.Msg)
	w.Int32(2, int32(m.Seq))
	for _, e := range m.Tags {
		w.RawString(3, e)
	}
	return w.Result()
}

func (m *PingRequest) UnmarshalZap(b []byte) error {
	r := zaprpc.NewReader(b)
	for r.Next() {
		switch r.Field() {
		case 1:
			m.Msg = r.String()
		case 2:
			m.Seq = int32(r.Int32())
		case 3:
			m.Tags = append(m.Tags, r.String())
		default:
			r.Skip()
		}
	}
	return r.Err()
}

type PingResponse struct {
	Msg string // 1
	Seq int32  // 2
}

func (m *PingResponse) GetMsg() string {
	if m == nil {
		return ""
	}
	return m.Msg
}
func (m *PingResponse) GetSeq() int32 {
	if m == nil {
		return 0
	}
	return m.Seq
}

func (m *PingResponse) MarshalZap() []byte {
	w := zaprpc.NewWriter()
	w.String(1, m.Msg)
	w.Int32(2, int32(m.Seq))
	return w.Result()
}

func (m *PingResponse) UnmarshalZap(b []byte) error {
	r := zaprpc.NewReader(b)
	for r.Next() {
		switch r.Field() {
		case 1:
			m.Msg = r.String()
		case 2:
			m.Seq = int32(r.Int32())
		default:
			r.Skip()
		}
	}
	return r.Err()
}

// EchoServer is the service interface (implement + Register).
type EchoServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

const (
	codeEchoPing uint8 = 1
)

func RegisterEchoServer(s *zaprpc.Server, impl EchoServer) {
	s.Handle(codeEchoPing, func(ctx context.Context, req []byte) ([]byte, error) {
		var in PingRequest
		if err := in.UnmarshalZap(req); err != nil {
			return nil, err
		}
		out, err := impl.Ping(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out.MarshalZap(), nil
	})
}

type EchoClient struct {
	C    *zaprpc.Client
	Addr string
}

func NewEchoClient(c *zaprpc.Client, addr string) *EchoClient {
	return &EchoClient{C: c, Addr: addr}
}
func (x *EchoClient) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	resp, err := x.C.Call(ctx, x.Addr, codeEchoPing, req.MarshalZap())
	if err != nil {
		return nil, err
	}
	var res PingResponse
	if err := res.UnmarshalZap(resp); err != nil {
		return nil, err
	}
	return &res, nil
}
