// Code generated by protoc-gen-zap. DO NOT EDIT.
// source: remote.proto
//
// Protobuf-free: plain structs + hand-rolled TLV codec over ZAP. The
// .proto is the one-time schema source; this output replaces the .pb.go.

package gentest

import (
	zaprpc "github.com/hanzoai/s3/s3/zaprpc"
)

type RemoteConf struct {
	Type                            string // 1
	Name                            string // 2
	S3AccessKey                     string // 4
	S3SecretKey                     string // 5
	S3Region                        string // 6
	S3Endpoint                      string // 7
	S3StorageClass                  string // 8
	S3ForcePathStyle                bool   // 9
	S3SupportTagging                bool   // 13
	S3V4Signature                   bool   // 11
	GcsGoogleApplicationCredentials string // 10
	GcsProjectId                    string // 12
	AzureAccountName                string // 15
	AzureAccountKey                 string // 16
	BackblazeKeyId                  string // 20
	BackblazeApplicationKey         string // 21
	BackblazeEndpoint               string // 22
	BackblazeRegion                 string // 23
	AliyunAccessKey                 string // 25
	AliyunSecretKey                 string // 26
	AliyunEndpoint                  string // 27
	AliyunRegion                    string // 28
	TencentSecretId                 string // 30
	TencentSecretKey                string // 31
	TencentEndpoint                 string // 32
	BaiduAccessKey                  string // 35
	BaiduSecretKey                  string // 36
	BaiduEndpoint                   string // 37
	BaiduRegion                     string // 38
	WasabiAccessKey                 string // 40
	WasabiSecretKey                 string // 41
	WasabiEndpoint                  string // 42
	WasabiRegion                    string // 43
	FilebaseAccessKey               string // 60
	FilebaseSecretKey               string // 61
	FilebaseEndpoint                string // 62
	StorjAccessKey                  string // 65
	StorjSecretKey                  string // 66
	StorjEndpoint                   string // 67
	ContaboAccessKey                string // 68
	ContaboSecretKey                string // 69
	ContaboEndpoint                 string // 70
	ContaboRegion                   string // 71
}

func (m *RemoteConf) GetType() string {
	if m == nil {
		return ""
	}
	return m.Type
}
func (m *RemoteConf) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}
func (m *RemoteConf) GetS3AccessKey() string {
	if m == nil {
		return ""
	}
	return m.S3AccessKey
}
func (m *RemoteConf) GetS3SecretKey() string {
	if m == nil {
		return ""
	}
	return m.S3SecretKey
}
func (m *RemoteConf) GetS3Region() string {
	if m == nil {
		return ""
	}
	return m.S3Region
}
func (m *RemoteConf) GetS3Endpoint() string {
	if m == nil {
		return ""
	}
	return m.S3Endpoint
}
func (m *RemoteConf) GetS3StorageClass() string {
	if m == nil {
		return ""
	}
	return m.S3StorageClass
}
func (m *RemoteConf) GetS3ForcePathStyle() bool {
	if m == nil {
		return false
	}
	return m.S3ForcePathStyle
}
func (m *RemoteConf) GetS3SupportTagging() bool {
	if m == nil {
		return false
	}
	return m.S3SupportTagging
}
func (m *RemoteConf) GetS3V4Signature() bool {
	if m == nil {
		return false
	}
	return m.S3V4Signature
}
func (m *RemoteConf) GetGcsGoogleApplicationCredentials() string {
	if m == nil {
		return ""
	}
	return m.GcsGoogleApplicationCredentials
}
func (m *RemoteConf) GetGcsProjectId() string {
	if m == nil {
		return ""
	}
	return m.GcsProjectId
}
func (m *RemoteConf) GetAzureAccountName() string {
	if m == nil {
		return ""
	}
	return m.AzureAccountName
}
func (m *RemoteConf) GetAzureAccountKey() string {
	if m == nil {
		return ""
	}
	return m.AzureAccountKey
}
func (m *RemoteConf) GetBackblazeKeyId() string {
	if m == nil {
		return ""
	}
	return m.BackblazeKeyId
}
func (m *RemoteConf) GetBackblazeApplicationKey() string {
	if m == nil {
		return ""
	}
	return m.BackblazeApplicationKey
}
func (m *RemoteConf) GetBackblazeEndpoint() string {
	if m == nil {
		return ""
	}
	return m.BackblazeEndpoint
}
func (m *RemoteConf) GetBackblazeRegion() string {
	if m == nil {
		return ""
	}
	return m.BackblazeRegion
}
func (m *RemoteConf) GetAliyunAccessKey() string {
	if m == nil {
		return ""
	}
	return m.AliyunAccessKey
}
func (m *RemoteConf) GetAliyunSecretKey() string {
	if m == nil {
		return ""
	}
	return m.AliyunSecretKey
}
func (m *RemoteConf) GetAliyunEndpoint() string {
	if m == nil {
		return ""
	}
	return m.AliyunEndpoint
}
func (m *RemoteConf) GetAliyunRegion() string {
	if m == nil {
		return ""
	}
	return m.AliyunRegion
}
func (m *RemoteConf) GetTencentSecretId() string {
	if m == nil {
		return ""
	}
	return m.TencentSecretId
}
func (m *RemoteConf) GetTencentSecretKey() string {
	if m == nil {
		return ""
	}
	return m.TencentSecretKey
}
func (m *RemoteConf) GetTencentEndpoint() string {
	if m == nil {
		return ""
	}
	return m.TencentEndpoint
}
func (m *RemoteConf) GetBaiduAccessKey() string {
	if m == nil {
		return ""
	}
	return m.BaiduAccessKey
}
func (m *RemoteConf) GetBaiduSecretKey() string {
	if m == nil {
		return ""
	}
	return m.BaiduSecretKey
}
func (m *RemoteConf) GetBaiduEndpoint() string {
	if m == nil {
		return ""
	}
	return m.BaiduEndpoint
}
func (m *RemoteConf) GetBaiduRegion() string {
	if m == nil {
		return ""
	}
	return m.BaiduRegion
}
func (m *RemoteConf) GetWasabiAccessKey() string {
	if m == nil {
		return ""
	}
	return m.WasabiAccessKey
}
func (m *RemoteConf) GetWasabiSecretKey() string {
	if m == nil {
		return ""
	}
	return m.WasabiSecretKey
}
func (m *RemoteConf) GetWasabiEndpoint() string {
	if m == nil {
		return ""
	}
	return m.WasabiEndpoint
}
func (m *RemoteConf) GetWasabiRegion() string {
	if m == nil {
		return ""
	}
	return m.WasabiRegion
}
func (m *RemoteConf) GetFilebaseAccessKey() string {
	if m == nil {
		return ""
	}
	return m.FilebaseAccessKey
}
func (m *RemoteConf) GetFilebaseSecretKey() string {
	if m == nil {
		return ""
	}
	return m.FilebaseSecretKey
}
func (m *RemoteConf) GetFilebaseEndpoint() string {
	if m == nil {
		return ""
	}
	return m.FilebaseEndpoint
}
func (m *RemoteConf) GetStorjAccessKey() string {
	if m == nil {
		return ""
	}
	return m.StorjAccessKey
}
func (m *RemoteConf) GetStorjSecretKey() string {
	if m == nil {
		return ""
	}
	return m.StorjSecretKey
}
func (m *RemoteConf) GetStorjEndpoint() string {
	if m == nil {
		return ""
	}
	return m.StorjEndpoint
}
func (m *RemoteConf) GetContaboAccessKey() string {
	if m == nil {
		return ""
	}
	return m.ContaboAccessKey
}
func (m *RemoteConf) GetContaboSecretKey() string {
	if m == nil {
		return ""
	}
	return m.ContaboSecretKey
}
func (m *RemoteConf) GetContaboEndpoint() string {
	if m == nil {
		return ""
	}
	return m.ContaboEndpoint
}
func (m *RemoteConf) GetContaboRegion() string {
	if m == nil {
		return ""
	}
	return m.ContaboRegion
}

func (m *RemoteConf) MarshalZap() []byte {
	w := zaprpc.NewWriter()
	w.String(1, m.Type)
	w.String(2, m.Name)
	w.String(4, m.S3AccessKey)
	w.String(5, m.S3SecretKey)
	w.String(6, m.S3Region)
	w.String(7, m.S3Endpoint)
	w.String(8, m.S3StorageClass)
	w.Bool(9, m.S3ForcePathStyle)
	w.Bool(13, m.S3SupportTagging)
	w.Bool(11, m.S3V4Signature)
	w.String(10, m.GcsGoogleApplicationCredentials)
	w.String(12, m.GcsProjectId)
	w.String(15, m.AzureAccountName)
	w.String(16, m.AzureAccountKey)
	w.String(20, m.BackblazeKeyId)
	w.String(21, m.BackblazeApplicationKey)
	w.String(22, m.BackblazeEndpoint)
	w.String(23, m.BackblazeRegion)
	w.String(25, m.AliyunAccessKey)
	w.String(26, m.AliyunSecretKey)
	w.String(27, m.AliyunEndpoint)
	w.String(28, m.AliyunRegion)
	w.String(30, m.TencentSecretId)
	w.String(31, m.TencentSecretKey)
	w.String(32, m.TencentEndpoint)
	w.String(35, m.BaiduAccessKey)
	w.String(36, m.BaiduSecretKey)
	w.String(37, m.BaiduEndpoint)
	w.String(38, m.BaiduRegion)
	w.String(40, m.WasabiAccessKey)
	w.String(41, m.WasabiSecretKey)
	w.String(42, m.WasabiEndpoint)
	w.String(43, m.WasabiRegion)
	w.String(60, m.FilebaseAccessKey)
	w.String(61, m.FilebaseSecretKey)
	w.String(62, m.FilebaseEndpoint)
	w.String(65, m.StorjAccessKey)
	w.String(66, m.StorjSecretKey)
	w.String(67, m.StorjEndpoint)
	w.String(68, m.ContaboAccessKey)
	w.String(69, m.ContaboSecretKey)
	w.String(70, m.ContaboEndpoint)
	w.String(71, m.ContaboRegion)
	return w.Result()
}

func (m *RemoteConf) UnmarshalZap(b []byte) error {
	r := zaprpc.NewReader(b)
	for r.Next() {
		switch r.Field() {
		case 1:
			m.Type = r.String()
		case 2:
			m.Name = r.String()
		case 4:
			m.S3AccessKey = r.String()
		case 5:
			m.S3SecretKey = r.String()
		case 6:
			m.S3Region = r.String()
		case 7:
			m.S3Endpoint = r.String()
		case 8:
			m.S3StorageClass = r.String()
		case 9:
			m.S3ForcePathStyle = r.Bool()
		case 13:
			m.S3SupportTagging = r.Bool()
		case 11:
			m.S3V4Signature = r.Bool()
		case 10:
			m.GcsGoogleApplicationCredentials = r.String()
		case 12:
			m.GcsProjectId = r.String()
		case 15:
			m.AzureAccountName = r.String()
		case 16:
			m.AzureAccountKey = r.String()
		case 20:
			m.BackblazeKeyId = r.String()
		case 21:
			m.BackblazeApplicationKey = r.String()
		case 22:
			m.BackblazeEndpoint = r.String()
		case 23:
			m.BackblazeRegion = r.String()
		case 25:
			m.AliyunAccessKey = r.String()
		case 26:
			m.AliyunSecretKey = r.String()
		case 27:
			m.AliyunEndpoint = r.String()
		case 28:
			m.AliyunRegion = r.String()
		case 30:
			m.TencentSecretId = r.String()
		case 31:
			m.TencentSecretKey = r.String()
		case 32:
			m.TencentEndpoint = r.String()
		case 35:
			m.BaiduAccessKey = r.String()
		case 36:
			m.BaiduSecretKey = r.String()
		case 37:
			m.BaiduEndpoint = r.String()
		case 38:
			m.BaiduRegion = r.String()
		case 40:
			m.WasabiAccessKey = r.String()
		case 41:
			m.WasabiSecretKey = r.String()
		case 42:
			m.WasabiEndpoint = r.String()
		case 43:
			m.WasabiRegion = r.String()
		case 60:
			m.FilebaseAccessKey = r.String()
		case 61:
			m.FilebaseSecretKey = r.String()
		case 62:
			m.FilebaseEndpoint = r.String()
		case 65:
			m.StorjAccessKey = r.String()
		case 66:
			m.StorjSecretKey = r.String()
		case 67:
			m.StorjEndpoint = r.String()
		case 68:
			m.ContaboAccessKey = r.String()
		case 69:
			m.ContaboSecretKey = r.String()
		case 70:
			m.ContaboEndpoint = r.String()
		case 71:
			m.ContaboRegion = r.String()
		default:
			r.Skip()
		}
	}
	return r.Err()
}

type RemoteStorageMapping struct {
	Mappings                 map[string]*RemoteStorageLocation // 1
	PrimaryBucketStorageName string                            // 2
}

func (m *RemoteStorageMapping) GetMappings() map[string]*RemoteStorageLocation {
	if m == nil {
		return nil
	}
	return m.Mappings
}
func (m *RemoteStorageMapping) GetPrimaryBucketStorageName() string {
	if m == nil {
		return ""
	}
	return m.PrimaryBucketStorageName
}

func (m *RemoteStorageMapping) MarshalZap() []byte {
	w := zaprpc.NewWriter()
	for k, v := range m.Mappings {
		ew := zaprpc.NewWriter()
		ew.String(1, k)
		ew.Message(2, v.MarshalZap())
		w.Message(1, ew.Result())
	}
	w.String(2, m.PrimaryBucketStorageName)
	return w.Result()
}

func (m *RemoteStorageMapping) UnmarshalZap(b []byte) error {
	r := zaprpc.NewReader(b)
	for r.Next() {
		switch r.Field() {
		case 1:
			if m.Mappings == nil {
				m.Mappings = map[string]*RemoteStorageLocation{}
			}
			er := zaprpc.NewReader(r.Message())
			var mk string
			var mv *RemoteStorageLocation
			mv = &RemoteStorageLocation{}
			for er.Next() {
				switch er.Field() {
				case 1:
					mk = er.String()
				case 2:
					_ = mv.UnmarshalZap(er.Message())
				default:
					er.Skip()
				}
			}
			m.Mappings[mk] = mv
		case 2:
			m.PrimaryBucketStorageName = r.String()
		default:
			r.Skip()
		}
	}
	return r.Err()
}

type RemoteStorageLocation struct {
	Name                   string // 1
	Bucket                 string // 2
	Path                   string // 3
	ListingCacheTtlSeconds int32  // 4
}

func (m *RemoteStorageLocation) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}
func (m *RemoteStorageLocation) GetBucket() string {
	if m == nil {
		return ""
	}
	return m.Bucket
}
func (m *RemoteStorageLocation) GetPath() string {
	if m == nil {
		return ""
	}
	return m.Path
}
func (m *RemoteStorageLocation) GetListingCacheTtlSeconds() int32 {
	if m == nil {
		return 0
	}
	return m.ListingCacheTtlSeconds
}

func (m *RemoteStorageLocation) MarshalZap() []byte {
	w := zaprpc.NewWriter()
	w.String(1, m.Name)
	w.String(2, m.Bucket)
	w.String(3, m.Path)
	w.Int32(4, int32(m.ListingCacheTtlSeconds))
	return w.Result()
}

func (m *RemoteStorageLocation) UnmarshalZap(b []byte) error {
	r := zaprpc.NewReader(b)
	for r.Next() {
		switch r.Field() {
		case 1:
			m.Name = r.String()
		case 2:
			m.Bucket = r.String()
		case 3:
			m.Path = r.String()
		case 4:
			m.ListingCacheTtlSeconds = int32(r.Int32())
		default:
			r.Skip()
		}
	}
	return r.Err()
}
